### ISSUE TITLE
adTypeElement in VASTParser.parseAdElement in ie9 not support set id

### ISSUE THREAD

**Issue by rubeniskov** [dailymotion/vast-client-js#105]
As you can see the code raise an error in ie9, I will send you and a pull-request to solve this

Kind regards!

<img width="1437" alt="captura de pantalla 2016-07-22 a las 0 38 46" src="https://cloud.githubusercontent.com/assets/6261914/17041281/575f2f10-4fa5-11e6-8776-79314eaf3fe4.png">

PR https://github.com/dailymotion/vast-client-js/pull/106

**Comment by rubeniskov** [comment]
PR: https://github.com/dailymotion/vast-client-js/pull/106

**Comment by michaelvial** [comment]
Fixed in #111
