### ISSUE TITLE
Extract CompanionClickTracking value from companion ads

### ISSUE THREAD

**Issue by TLFyber** [dailymotion/vast-client-js#107]
According to the [VAST spec](http://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf), companion ads can have an optional CompanionClickTracking property which "contains a URI to a location or file that the video player should request when the user clicks on the companion creative." Currently the client extracts the CompanionClickThrough property but doesn't extract CompanionClickTracking. Would it be possible to add support for this property to the VAST client?

It seems like it might be a small change to that part of the parser code but I couldn't tell if there would be any side-effects or potential problems resulting from modifying it:
https://github.com/dailymotion/vast-client-js/blob/master/src/parser.coffee#L388

Ideally the value would be returned on the companion ad object as something like 
companionAd.companionClickTrackingURLTemplate

**Comment by TLFyber** [comment]
I created a PR with a suggested way of solving this issue:
https://github.com/dailymotion/vast-client-js/pull/108

**Comment by michaelvial** [comment]
Fixed in 9d8d6dc353e9476f5bc4fe7f98326563da240179

**Comment by TLFyber** [comment]
Sorry to re-open this, it appears the PR i submitted before won't support all VAST tags which use this feature. I submitted another PR to correct this:
https://github.com/dailymotion/vast-client-js/pull/109
