### ISSUE TITLE
Catch HTTPS-->HTTP error

### ISSUE THREAD

**Issue by ngehlert** [dailymotion/vast-client-js#116]
I want to show a VAST Preview on my HTTPS site, the user can provide VASTs with their videos.

Some users however use insecure HTTP videos. In the vast-client.js there is a separate check to catch and throw an error in that case.
But I was not able to catch that error inside my DMVAST.client.get() call.

Is there any way to catch that error so I can provide a specific error handling to the user?

Error Handling in vast-client.js (parsed from xmlhttprequest.coffee)
> XHRURLHandler.get = function(url, options, cb) {
    var xhr;
    if (window.location.protocol === 'https:' && url.indexOf('http://') === 0) {
      return cb(new Error('Cannot go from HTTPS to HTTP.'));
    }
   ...

**Comment by michaelvial** [comment]
Well, you're right, there is no way to catch errors raised inside `DMVAST.client.get()` call. Well spotted bug.
We'll have to rewrite quite some code to fix this issue, and make some change in the API, so the proper fix will be foe the next major release. 

In the meantime, you can use a custom `urlHandler` component to handle the HTTPS - > HTTP error. Something like

``` coffee
# My function
handleUnsecureURL = ->
  alert('Please provide an https url')

# Custom handler
customUrlhandler =
  supported: -> true
  get: (url, options, cb) ->
    # HTTPS test
    if window.location.protocol == 'https:' && url.indexOf('http://') == 0
      return handleUnsecureURL()
    # Ajax call
    $.get(url)
      .done (data) -> cb(null, data)
      .fail (xhr, error) -> cb(error, null)

# Parse url using customUrlhandler
DMVAST.client.get url, {urlhandler: customUrlhandler}, (vast) ->
  console.log(vast)
```

Thx @ngehlert for reporting this problem.

**Comment by ngehlert** [comment]
awesome thanks for the response and the workaround. 
i'll stay tuned for the next major release :)
do you have a rough idea when the next major release will be?

**Comment by michaelvial** [comment]
no, but we're gonna have to move from `coffee` to `es6` and break things :)
