### ISSUE TITLE
ClickThrough node is null.

### ISSUE THREAD

**Issue by Grafluxe** [dailymotion/vast-client-js#128]
The ClickThrough node in VideoClicks returns null. Note that the ClickTracking node works as expected.

```
<VideoClicks>
  <ClickThrough>...</ClickThrough>
  <ClickTracking id="test1">...</ClickTracking>
  <ClickTracking id="test2">...</ClickTracking>
</VideoClicks>
```

**Comment by Grafluxe** [comment]
This issue only happens when wrappers are involved.

**Comment by michaelvial** [comment]
Hi @Grafluxe . I've done a quick test with a VAST wrapper and I've access to the creative `ClickThrough` URL:
``` javascript
// Fake url returning a VAST wrapper
DMVAST.client.get('http://example.dailymotion.com/vast_wrapper.xml', function(response, error)
{
  console.log(response.ads[0].creatives[0].videoClickThroughURLTemplate)
});
```

Can you provide me a VAST file where I can reproduce your issue?

**Comment by Grafluxe** [comment]
Thanks for the quick reply @michaelvial.

I'm experiencing problems when the VASTWrapper has a VideoClickThrough URL, but no VideoClicks node is present in the corresponding VAST response.

Instead of keeping the ClickThrough URL from the VASTWrapper, the logic overwrites the value with null.

VASTWrapper:

```
<VideoClicks>
    <ClickThrough><![CDATA[http://www.example.com/support]]></ClickThrough>
    <ClickTracking id="DART"><![CDATA[http://example.com]]></ClickTracking>
</VideoClicks>
```

**Comment by michaelvial** [comment]
@Grafluxe Can you tell me if #129 fix your problem?

**Comment by Grafluxe** [comment]
I pulled and retried. It's still not working.

**Comment by michaelvial** [comment]
Ok Can you provide me a GIST where I can find both wrapper an inline VAST files?

**Comment by Grafluxe** [comment]
I retried again, but this time checking out the 'vast2_wrapper_clickthrough_support' branch specifically and re-running 'npm install' and 'npm run bundle'. It works now. 

Thank you for all your help.

**Comment by Grafluxe** [comment]
@michaelvial, the URI looks to be working fine, but the 'ClickTracking' data from the wrapper is not be pushed into the 'videoClickTrackingURLTemplates' array as expected.

Example 
(note, I removed the CDATA syntax for brevity)

XML 1:
```
<VideoClicks>
  <ClickTracking id="DART">http://test.net/click-tracker(1,2)</ClickTracking>
  <ClickTracking id="ThirdParty">http://test.net?click-tracker(2,2)</ClickTracking>
</VideoClicks>
```

XML 2:
```
<VideoClicks>
  <ClickThrough>http://www.test.com/support/WRAPPER</ClickThrough>
  <ClickTracking id="WRAP">http://test.net/click-tracker/WRAPPER</ClickTracking>
 </VideoClicks>
```

XML 3:
```
<VideoClicks>
  <ClickTracking id="AD">http://test.net/click-tracker/AD</ClickTracking>
</VideoClicks>
```

Output:
```
videoClickThroughURLTemplate: "http://www.google.com/support/richmedia/WRAPPER"
videoClickTrackingURLTemplates: Array[3]
  [0]: "http://ad.doubleclick.net/click-tracker/AD"
  [1]: "http://ad.doubleclick.net/click-tracker(1,2)"
  [2]: "http://ad.doubleclick.net?click-tracker(2,2)"
```

**Comment by michaelvial** [comment]
@Grafluxe I've updated #129 and added some unit test about your scenario (Wrapper -> wrapper > inline ), but I wasn't able te reproduce your bug.

Can you put the 3 VAST XML file you use for this bug on a GIST so I can reproduce it?

**Comment by Grafluxe** [comment]
After more testing, we see that the issue occurs when a second creative node exists in the wrapper.
https://gist.github.com/Grafluxe/d159836c39339303bc340e547c37e010

**Comment by michaelvial** [comment]
I've found the problem, thanks to your GIST. Can you pull #129 last commit and tell me if it works?

**Comment by Grafluxe** [comment]
You're welcome and thank you. It works as expected now.
Will you be merging soon so that I can npm update?

**Comment by michaelvial** [comment]
We'll try to do a release tomorrow.

**Comment by Grafluxe** [comment]
Great. Thanks again.
