### ISSUE TITLE
Impression urls getting fired before actual ad start

### ISSUE THREAD

**Issue by rgulrajani** [dailymotion/vast-client-js#130]
Hi Michael,

I was looking at the tracker code and noticed that the impression URLs are dispatched when load is called on the VASTTracker.
As per IAB standards for video ads, the impressions should get dispatched after the ad has started playing.
Also, when the ads fails, the impression is getting logged in case of a VPAID ad.

Do you think this is an issue and if yes, will be addressed in the vast-client?

**Comment by michaelvial** [comment]
Hi @rgulrajani 

1) According to [VAST 3.0](https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf#page=18) spec, the impression URLs have to been called when the 1st frame of the ad is displayed. In the API documentation, we call `VASTTracker.load()`  when we receive the videoTag `canPlay` event.
The [MDN doc](https://developer.mozilla.org/en/docs/Web/Guide/Events/Media_events) says about `canPlay`
> Sent when enough data is available that the media can be played, at least for a couple of frames.
It looks valid to me. But I agree that the method name isn't the best.

2) I'm not sure to get it, there no VPAID loader in this lib. Do we (in general) have to log the impression URLs on VPAID errors? Anyway, the impression URLs are never called on there own, it has do be done via `VASTTracker.load()` method.

**Comment by rgulrajani** [comment]
Hi @michaelvial 

Thanks for your response.

1. Though I understand when you say that the VAST 3.0 spec says that the impression should be fired when the first frame of the ad is played. But the canPlay event, only mentions that the ad can be played. It does not imply that the ad has started playing and the first frame is played. 

I would imagine that the impression urls get dispatched after the ad has actually started playing, rather than when the ad can be played.
I think when the vast-client gets the start event, would be the best time to dispatch the impression urls to be compliant with the IAB specs.

2. Also for a vpaidAd, when there is a failure like the ad cannot play, the vast-client still dispatches the impression urls. (We even tried it by commenting the startAd call on the ad and the impressions were still fired.)

If the vast-client fires the impressions when the start event is received, it would resolve both of the above.

Let me know what you think.

Thanks.

**Comment by michaelvial** [comment]
If you consider you'll only set up the `VASTTracker` when the user has specificaly asked to play the video, the `canPlay` will happen at the 1st playing frames of the video. You shouldn't set up the `VASTTracker` if your player is not in a state of playing the video. Still, this is just an example for the documentation, you are free to call the `VASTTracker.load()` method whenever you feel it's the most appropriate time.

For the 2nd point, this library doesn't provide any VPAID loader, you have to manually call `VASTTracker.load()` to log the impressions URLs. It sounds like you're using a lib that rely on the VAST client but call `VASTTracker.load()` at the wrong moment/event.

**Comment by rgulrajani** [comment]
@michaelvial 
Thanks for your reply.
Was able to sort this out with the load() method on the VAST tracker.
