### ISSUE TITLE
Wrapper CustomClick URIs are being ignored.

### ISSUE THREAD

**Issue by Grafluxe** [dailymotion/vast-client-js#132]
The ad objects 'videoCustomClickURLTemplates' property is ignoring wrapper nodes.

**Comment by michaelvial** [comment]
Hi @Grafluxe,

You're right, the parser didn't bundle `<CustomClicks>` URLS as it should. I've created PR #133 to fix it.

**Comment by Grafluxe** [comment]
Sounds good. Thanks.
Do you have a planned release date?

**Comment by michaelvial** [comment]
In the next few days I think, I've to fix another bug as well.
