### ISSUE TITLE
Ad parse failure on URI encoded query strings

### ISSUE THREAD

**Issue by Grafluxe** [dailymotion/vast-client-js#139]
Encoded query strings (in the media URI) are cause the ad parse logic to fail.

```
<MediaFiles>
  <MediaFile apiFramework="VPAID" type="application/javascript" delivery="progressive" ...>
    <![CDATA[parser.js?adData=http%3A%2F%2Fad.com%2F%3Fcb%3D%5Btime%5D]]>
    </MediaFile>
</MediaFiles>
```

Note: using decodeURIComponent solves the issue.

**Comment by michaelvial** [comment]
Hi @Grafluxe 

I was unable to reproduce the bug. I've update the `sample.xml` with your mediaFile, but it gets correctly parsed: See #143

**Comment by Grafluxe** [comment]
Thanks for testing it. When running through a player, I get the error `Uncaught TypeError: Cannot read property 'slice' of null`
 
See vast-client/dist/parser.js :184

**Comment by michaelvial** [comment]
Seems there is no issue with URI encoded query strings.
