### ISSUE TITLE
DMVAST usage example

### ISSUE THREAD

**Issue by giannoudak** [dailymotion/vast-client-js#141]
Hello, and congruts for this tool!

I'm trying a create a player using the DMVAST client, but i can't clearly figure out how to use it
Are there any more analytical examples on this.

I am using the flow bellow:
i am requesting a vast code as bellow, parse the video URL, create a Vast tracker and then create a video element dynamically with the video url

``` javascript
	DMVAST.client.get('http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=is&c=23&pl=VAST&pli=14222276&PluID=0&pos=1901&ord=[timestamp]&cim=1', function(response, error)
		{
			// process the VAST response
			var VAST = response;
			var videoURL = response.ads["0"].creatives["0"].mediaFiles["0"].fileURL;


			// Create a VAST Tracker instance
			var vastTracker = new DMVAST.tracker(response.ads["0"], response.ads["0"].creatives["0"]);
		

			var content = document.getElementById("story_body");
			var video = document.createElement("video");
			video.controls = true;
			video.muted = true;
			video.src = videoURL;
			video.load();
```

After that, how do i call any tracking events? or they are fired automatically?
Also, Is it supposed to show the skip button automatically, or do i have to saw it manually, and how?

**Comment by michaelvial** [comment]
Hi @giannoudak 

I agree with you, we're clearly missing some documentation about how to use the VAST client. This lib just provides a VAST parser and a tracker. However, you have to do the integration with the video player. You have to provide some info to the tracker so it can ping the tracking URLs. I've done a quick JsBin with a skippable linear ad to show you the basic:

https://jsbin.com/wayukaw/edit?html,js,output
If you don't have an ad, keep refreshing and you should get one.

Some tracking is missing (like `play`, `pause`, `mute`... full list [here](https://github.com/dailymotion/vast-client-js/blob/master/docs/api.md#setmuted-muted-)) but all the important ones are there.

Hope it helps.

**Comment by giannoudak** [comment]
Hi @michaelvial 
Thanks for the demo. Its really very helpfull!
The VAST tag i was checking had a wrong duration tag set and as a result, the tracking events were firing earlier.

Actually, this tool is only for VAST or it can also work with VPAID tags?

thanks again a lot

**Comment by michaelvial** [comment]
Only for VAST

**Comment by dharFr** [comment]
@michaelvial What about adding the link to your jsbin to the README, so that everyone can benefit from it?

**Comment by michaelvial** [comment]
I want to clean it first ^^

**Comment by flasheye** [comment]
@giannoudak i use it with VPAID too. not so difficult, but you have to call the tracking Events manually.  

The important thing is to call the duration, because the VAST dont know the duration from VPAID: 
vastTracker.setDuration(xxx);
Then the tracking events wont firing earlier.

When no duration is set, but only firstQuartile, mid or third you can call:
vastTracker.track("firstQuartile", true);

Whats not working: Custom CLICK URLs from VPAID.
vastTracker.click(customVpaidUrl);
Maybe @michaelvial can modify it ;)

**Comment by eliamaino-fp** [comment]
https://github.com/dailymotion/vast-client-js/releases/tag/2.0.0 Introduced a completely reworked documentation. Feel free to suggest any improvement if some parts of it are still not clear enough.
