### ISSUE TITLE
NonLinear missing maintainAspectRatio and scalable

### ISSUE THREAD

**Issue by flasheye** [dailymotion/vast-client-js#145]
Hi!
Unfortunately, I do not find "scalable" and "maintainAspectRatio" at "VASTParser.parseNonLinear"
https://www.iab.net/media/file/VAST-2_0-FINAL.pdf (13/16)

Its not required but it would be fine :)
i think this is missing too:
expandedWidth
expandedHeight

BR,
Christian

**Comment by michaelvial** [comment]
Will be fixed in #147
