### ISSUE TITLE
"minSuggestedDuration" in seconds (as duration)

### ISSUE THREAD

**Issue by flasheye** [dailymotion/vast-client-js#146]
Hi,
i like this tool so much :) Thanks for the good work! 👍 

With nonLinear Ads you return the duration: "00:00:30" and with linearAds: "30".
Maybe something like this would be fine:

nonlinearAd.minSuggestedDuration = this.parseDuration(nonlinearResource.getAttribute("minSuggestedDuration"));

Thanks :)

**Comment by michaelvial** [comment]
Will be fixed in #147
