### ISSUE TITLE
Request for AltText for StaticResource companion ad

### ISSUE THREAD

**Issue by giannoudak** [dailymotion/vast-client-js#154]
Hello and thanks for this great tool!

We noticed that the parser doesn't parse altText attribute if a staticresource is being served
in file vast-client-js/src/companionad.coffee the VASTCompanionAd class doen't define an alttext property
``` javascript
class VASTCompanionAd
    constructor: ->
        @id = null
        @width = 0
        @height = 0
        @type = null
        @staticResource = null
        @htmlResource = null
        @iframeResource = null
        @companionClickThroughURLTemplate = null
        @trackingEvents = {}

module.exports = VASTCompanionAd
```
Is this a bug? or is there any other way we can fetch the alttext property?
Is this going to be developed?

thanks a lot in advance

**Comment by vagelkara** [comment]
I found a solution that could be help someone:

Just add this, at companionad.coffee, so you declare a new variable:
```coffeescript
 @altText = null
```

And change the parser.coffee as below:
```coffeescript
 for staticElement in @childsByName(companionResource, "StaticResource")
                companionAd.type = staticElement.getAttribute("creativeType") or 0
                for child in @childsByName(companionResource, "AltText")
                    companionAd.altText = @parseNodeText(child)
                companionAd.staticResource = @parseNodeText(staticElement)
```
@giannoudak

**Comment by michaelvial** [comment]
Sorry for the late reply @giannoudak, we've been quite busy lately and we didn't had time to adress the reported issues.

@vagelkara fix works well, and if one of you guys can do a PR that would be perfect (don't forget to update the unit test, it's pretty straight forward).
