### ISSUE TITLE
[Question]Active tracking for nonlinear/companion clickthrough

### ISSUE THREAD

**Issue by StevanCakic** [dailymotion/vast-client-js#158]
Hi,

I use this very nice parser for my project and currently, I can't  find a solution to active tracking clickthrough for nonlinear or companion ads. For example, for linear this:
ad - container for linear ad
tracker - new DMVAST.tracker(adv.ad, adv.creative)
           `

            //Set clickthrough on a linear ad.

            ad.addEventListener('click', function() {

                // Do VAST tracking for clickThrough

                tracker.click();

            });

            tracker.on('clickthrough', function(url) {

                log('clickthrough tracking URLs have been called - Linear');

                // Open clicktrough URL into a new window

                window.open(url);

            });
`

code works nice.
Any suggestions?

Thanks,
Stevan

**Comment by michaelvial** [comment]
Hi @StevanCakic,

Sorry for the really late reply. I've update the VAST parser/tracker to allow the use of `click()` for non-linear ads. You'll have to pass the selected `<companion>`/`<nonlinear>` element in order to make it work.

``` javascript
var ad = response.ads[0];
var creative = ad.creatives[0];
var variation = creative.variations[0]; // my selected nonlinear ad
var tracker = new DMVAST.tracker(ad, creative, variation);

// This following code will now call the nonLinearClickTracking urls
ad.addEventListener('click', function() {
  // Do VAST tracking for clickThrough
  tracker.click();
});

// And return the nonLinearClickThrough url
tracker.on('clickthrough', function(url) {
  log('clickthrough tracking URLs have been called - Linear');
  // Open clicktrough URL into a new window
  window.open(url);
});
```

Hope it'll fix your issue.
