### ISSUE TITLE
[Question] VPAID and this VAST parser

### ISSUE THREAD

**Issue by StevanCakic** [dailymotion/vast-client-js#166]
Hi,

can someone help me with VPAID? How can I use VPAID with this parser? Does anyone have any sample code for that? Any links?

Thanks

**Comment by michaelvial** [comment]
You gonna have to code the VPAID part, as this lib only provide a VAST parser and tracker. Quick example:
`````` javascript
// Set VAST tracker with select VPAID creative
var vastTracker = new DMVAST.tracker(ad, creative)

// Load VPAID ad unit as using creative.mediaFiles[0].fileURL 
// ....
// Bind the VPAID event listeners
vpaidAdUnit.subscribe('AdImpression', function() {
  // Ping VAST urls for impression
  vastTracker.load()
})
vpaidAdUnit.subscribe('AdVideoFirstQuartile', function() {
  // Ping VAST urls for 1st Quartile
  vastTracker.track('firstQuartile', true)
})
// And so on...

// Call VPAID initAd(), startAd() ...
``````
VASTTracker `track()` method can be found [here](https://github.com/dailymotion/vast-client-js/blob/master/src/tracker.coffee#L152) if you wanna see how it works.
You can find a table about VAST/VPAID events matching in the [VPAID2.0 spec](http://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf#page=14) .

**Comment by StevanCakic** [comment]
@michaelvial Thanks a lot!
