### ISSUE TITLE
Is VAST 2.0 supported?

### ISSUE THREAD

**Issue by nfepl** [dailymotion/vast-client-js#167]
Hi,

I'm testing this module with a VAST 2.0 url, but the method `DMVAST.client.get` it doesn't returns any object or error.
I've seen that there are some commits about VAST 2.0, so I was wondering if there's something wrong with what I'm doing.

The VAST url that was using is `http://ads.us.e-planning.net/eb/4/1cb7f/Home/test_vast_vp1?o=v&ma=1&vv=2`

**Comment by michaelvial** [comment]
Hi @nfepl ,

Just did a quick integration with your VAST everything seems to work:
https://jsbin.com/fiyemow/2/edit?html,js,console,output

**Comment by nfepl** [comment]
Hi @michaelvial,

Indeed it was working, after seeing your demo (it was pretty much what I was doing) I've double checked the js we were including and notice that it wasn't the latest.
Upon upgrading it, the response was correctly parsed.

Thank you very much for taking the time to respond and making that demo!
