### ISSUE TITLE
conflict with global requirejs

### ISSUE THREAD

**Issue by giannoudak** [dailymotion/vast-client-js#168]
Hi and thanks for this great tool!

we noticed an issue when having included the vast-client library in a site where already exists the requirejs lib. The test case includes that the requirejs is loaded before the vast-client.js
in case the requirejs exists on the client site we noticed in the bellow code (which is the first line of the vast-client.js)
```javascript
(function(f)
{
    if (typeof exports === "object" && typeof module !== "undefined") {
        module.exports = f()
    } else if (typeof define === "function" && define.amd) {
        define([], f)
    } else {
        var g;
        if (typeof window !== "undefined") {
            g = window
        } else if (typeof global !== "undefined") {
            g = global
        } else if (typeof self !== "undefined") {
            g = self
        } else {
            g = this
        }
        g.DMVAST = f()
    }
})
```
that the DMVAST is set by define and not in the window object.

if i want to load the DMVAST module as input in another custom module without requirejs, how should i do this?

**Comment by michaelvial** [comment]
Hi @giannoudak,

I don't know a lot about `requireJs`, but I think you can load the VastClient as a module using `require.config()` :
``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.14/require.js" type="text/javascript"></script>
<script type="text/javascript">
  require.config({
    paths: {
        "dmvast": "https://cdn.rawgit.com/dailymotion/vast-client-js/master/vast-client"
    },
    waitSeconds: 40
  });
</script>

<script type="text/javascript">
  require( ["dmvast"],
    function (dmvast) {
      console.log(dmvast)
    }
  );
</script>
```
[Js fiddle here](https://jsfiddle.net/michaelvial/gmv4ddz4/) 

This should work with the `/node_modules` VastClient file too
