### ISSUE TITLE
[Question]Which Linear Ad to play

### ISSUE THREAD

**Issue by StevanCakic** [dailymotion/vast-client-js#169]
Hi, 

I have some questions, and these questions are not about parser, it's a logical decisions, how you decide is linear <Ad> is preroll, postroll or midroll? Do you use <Ad> id attribute for that? As I saw from documentation this attribute isn't required, what you do when id isn't provided and maybe that id can't be informative, for example, if id="1" that is not so informative but if id="preroll-1" that is helpful? Also, if there is more than one <Ad> in VAST .xml sample document, how you decide which <Ad> to play? Maybe put <Ad>'s in one queue and when <Ad> completed start another from queue later (like mid-roll or post-roll). These parts are not strictly defined by VAST, I read documentations few times and I didn't find anything?

Thanks!

**Comment by michaelvial** [comment]
Sorry, really late reply, you probably have found an answer about that but anyway, that might help someone.

The VAST doesn't contain any information about its position in the in-stream timeline (`preroll`/ `midroll` / `postroll`). There is another XML based format named VMAP that does that : https://www.iab.com/guidelines/digital-video-multiple-ad-playlist-vmap-1-0-1/

If the VAST is returned by an adServer, they probably provide a GET param to define which position the ad should be played: eg:

```js
// Requesting a preroll from adserver
DMVAST.client.get('http://adserver.com/getVast.php?position=0', function(response, error) {
})
````
