### ISSUE TITLE
Vast 2.0 with 'skip' event in Extensions > CustomTracking

### ISSUE THREAD

**Issue by martinstender** [dailymotion/vast-client-js#174]
Hi all

Unfortunately, we are getting Vast 2.0 files from our ad-network and since 'skip' is not a part of Vast 2.0, they put that event in Extensions:
```
<Creatives>
...
</Creatives>
<Extensions>
  <Extension>
    <CustomTracking>
      <Tracking event="skip">
        <![CDATA[
          http://url-to-skip-event-here
        ]]>
      </Tracking>
   </CustomTracking>
</Extension>
```

Will I need to write some woodoo myself or is there anyway I can get vast-client to understand this special case?

Many thanks in advance :-)
Martin

**Comment by michaelvial** [comment]
I'm afraid it wont retrieve it correctly. The `<extension>` tag will be parsed but won't return all the info. I've run a test and I got:

``` Js
VASTParser.get(vastURL, function(response){
  console.log(response.ads[0].extensions[0].children[0])
})

// {
//  name: 'CustomTracking',
//  value: 'http://url-to-skip-event-here',
//  attributes: {} 
// }
```
Here is the function that parse the `<extensions>` tag : https://github.com/dailymotion/vast-client-js/blob/master/src/parser.coffee#L302

**Comment by martinstender** [comment]
Of course - and then I'll just roll my own tracking function. It was the parsing I was afraid I had to do myself... :-)

Many thanks - a big help!
