### ISSUE TITLE
Invoke firstQuartile, midpoint etc for VPAID

### ISSUE THREAD

**Issue by BenBao93** [dailymotion/vast-client-js#190]
Hi,

when a VAST contains a VPAID creative tracking is currently a bit difficult with the tracker. As far as I see the VPAID specs have no event/method to query the actual playback progress but will rather just dispatch VAST events to the player. Given that it is not possible to set the progress of the video correctly in the tracker.

A workaround would be to take the time from the XML and then calculate at which point the events would be dispatched, then send those times to the tracker progress method. Problem is that the AdDuration in XML is not necessarily the actual video time in the VPAID and not all VPAIDs provide the duration property, so calculating the event timing would often be incorrect and result in wrong or missed trackers.

Is there a way to direct trigger the time tracking events rather than just passing the time progress to the tracker?

**Comment by michaelvial** [comment]
Well, the best we can do is to rely on  the VPAID events (as specified in the [VPAID 2 spec page 15](https://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf#page=15)) You have to subscribe to the VPAID events and manually call the VAST `track` method. Quick example:
```js
// Initialise the vastTracker with selected ad & creative
var vastTracker = new DMVAST.tracker(ad, creative)

// Loading the vpaid script
iframe = document.createElement('iframe');
iframe.id = "adloaderframe";
document.body.appendChild(iframe);
// ‘url’ points to the ad js file
iframe.contentWindow.document.write('<script src="' + url + '"></scr' + 'ipt>');
var fn = iframe.contentWindow['getVPAIDAd'];
if (fn && typeof fn == 'function') {
 VPAIDCreative = fn();
}

// Tracking VAST firstQuartile pixels once
var onAdVideoFirstQuartile = function() {
  vastTracker.track('firstQuartile', true)
}

// Subscribing to VPAID events
VPAIDCreative.subscribe(onAdVideoFirstQuartile, 'AdVideoFirstQuartile')
```

**Comment by BenBao93** [comment]
Got it, that is actually exactly what I was looking for! The track function isn't in the docs for the tracker and I must have missed it while going through the code. Thanks!
