### ISSUE TITLE
'clickthrough' event only triggered on some tracker.click() calls

### ISSUE THREAD

**Issue by ScottyMJacobson** [dailymotion/vast-client-js#194]
I've noticed that the `clickthrough` event doesn't always fire

If I had to guess, it's a matter of this extra indentation in the `click` method (`tracker.coffee`):

```coffeescript

    # To be called when the user clicks on the creative
    click: ->
        if @clickTrackingURLTemplates?.length
            @trackURLs @clickTrackingURLTemplates

        if @clickThroughURLTemplate?
            if @linear
                variables = CONTENTPLAYHEAD: @progressFormated()
            clickThroughURL = VASTUtil.resolveURLTemplates([@clickThroughURLTemplate], variables)[0]

            @emit "clickthrough", clickThroughURL # <- <-

```

But since this expects the 'clickthroughURL' variable to be populated, it's not totally clear whether this event should actually be fired when there are only clickTracking URLs,

For my use case, I need the tracker instance to emit a `clickthrough` event regardless, so I'm creating a fork right now to implement it. Happy to pull request it in if `always firing` is the desired behavior

**Comment by michaelvial** [comment]
Hi @ScottyMJacobson 

Thanks for reporting the indentation issue . About the `clickthrough` event, do you do something in particular when you receive this event without a url?

**Comment by ScottyMJacobson** [comment]
>About the clickthrough event, do you do something in particular when you receive this event without a url?

Nope - for my use case I'm just adding a handler that doesn't take in any arguments for any time a `clickthrough` event is fired from the tracker
