### ISSUE TITLE
callback of DMVAST.parser.load is called with neither a response nor an error

### ISSUE THREAD

**Issue by Knotschi** [dailymotion/vast-client-js#195]
The documentation says:

* `Function` *done* – Method to be called once the VAST document is parsed. When at least 1 valid `<inline>` has been found, the 1st parameter will be an array of [`VASTAd`](https://github.com/dailymotion/vast-client-js/tree/master/src/ad.coffee) instances. Hoverwise, in case of no ads, it will be `null`, and an error as a 2nd parameter is provided.

But if the xml passed to the load function is a wrapper and the wrapper points to an empty vast tag, the callback is called with both parameters being null.

**Comment by michaelvial** [comment]
Thanks @Knotschi we will investiate that.

**Comment by eliamaino-fp** [comment]
Solved in https://github.com/dailymotion/vast-client-js/pull/198
