### ISSUE TITLE
Has anyone successfully get VPAID to work?

### ISSUE THREAD

**Issue by helven** [dailymotion/vast-client-js#196]
I am working on making my video player to support VPAID. This is the VPAID tag XML I'm working on
https://ads.stickyadstv.com/vast/vpaid-adapter/5590338

This is what I got so far.  I have no idea how do it initiates the ad by calling initAd() as mentioned in IAB VPAID document thus nothing is happening to my video player.

url is the javascript link i extracted from the XML
```
// Initialise the vastTracker with selected ad & creative
var vastTracker = new DMVAST.tracker(ad, creative)

// Loading the vpaid script
iframe = document.createElement('iframe');
iframe.id = "adloaderframe";
document.body.appendChild(iframe);
// ‘url’ points to the ad js file
iframe.contentWindow.document.write('<script src="' + url + '"></scr' + 'ipt>');
var fn = iframe.contentWindow['getVPAIDAd'];
if (fn && typeof fn == 'function') {
    VPAIDCreative = fn();
    VPAIDCreative.initAd(); // this gives javascript error
}
```
Any clue? What should I do next?

**Comment by michaelvial** [comment]
Hi @helven 
The iAB Vpaid specification as some examples on how to integrate a VPAID ad in javascript:
https://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf#page=48

**Comment by helven** [comment]
Hi @michaelvial 
Thanks for the link. I am coming from creating a video player that is able to parse a  javascript VPAID ad
I actually coming from page 47, that's how I get my VPAIDCreative variable. Base on my understanding, the example afterwards is about Ad Implementation, which is the skeleton on how an VPAID ad should be **implemented** than being **used** 

I notice there is this function that has to be in the ad but I can't find any example what exactly the parameter I should be passing into the ad from a Video Player perspective.
`LinearAd.prototype.initAd = function(width, height, viewMode, desiredBitrate, creativeData, environmentVars)`

**Comment by michaelvial** [comment]
Oh, you're right, there is no example on how to use vpaid.

You can find a schema on how to init a vpaid here: https://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf#page=17.

In your example, you need to call `VPAIDCreative.handshakeVersion()` before `VPAIDCreative.initAd()`. Also,`initAd` requires some parameters.

**Comment by Kasra-j** [comment]
following the same flow
```
iframe = document.createElement('iframe');
iframe.id = "adloaderframe";
document.body.appendChild(iframe);
// ‘url’ points to the ad js file
iframe.contentWindow.document.write('<script src="' + url + '"></scr' + 'ipt>');
var fn = iframe.contentWindow['getVPAIDAd'];
```
the "getVPAIDAd" function does exist inside the iframe, but `iframe.contentWindow['getVPAIDAd']` returns "undefined" for me!

@briganti or anyone else have any idea why?
