### ISSUE TITLE
Persistent storage handling

### ISSUE THREAD

**Issue by mseeley** [dailymotion/vast-client-js#204]
Hello Dailymotion 👋 . Our application imports the vast-client lib. Thank you very much for sharing it.

I have several observations I would appreciate your feedback on.

1. `VASTUtil.storage` requires `localStorage` or `sessionStorage`. We run on embedded devices. It's not unusual for devices to have experimental `localStorage` implementations. Have you considered allowing injection of different storage implementation that match the existing interface?
1. The keys for values stored by `vast-client` are not partitioned away from other keys. Eg, `lastSuccessfullAd`, `totalCalls`, `totalCallsTimeout` can overwrite other environment values or be themselves be overwritten unintentionally. This is a good opportunity for the `vast-client` to prefix its keys.
1. `__VASTUtil__` the key/value is set and retrieved but never removed. Desktop browsers have gobs of storage while embedded devices have far far less. While this is a little key and little value it would be kind to the host environment and app to cleanup after testing for a storage interface.

Thanks for your feedback.

**Comment by eliamaino-fp** [comment]
Hey @mseeley thanks for these suggestions. I'll go in order:

1.  We never had to deal with embedded `localStorage` implementations for the moment. I agree that it could be a good idea to provide a `storage` interface to allow to inject a custom implementation.
2. Yes, the current implementation is not the safest in terms of naming. We'll take it in consideration
3. Totally agree :)

Anyway we're currently working on a `2.0` release which will introduce many changes in the current APIs, therefore thanks for the feedback we'll definitely take it into account in the process.

**Comment by eliamaino-fp** [comment]
Custom storage support is now available from `2.0` release, see https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-client.md#storage-storage
