### ISSUE TITLE
Not a constructor

### ISSUE THREAD

**Issue by S4n60w3n** [dailymotion/vast-client-js#241]
Version 2.0.1 from [npm](https://www.npmjs.com/package/vast-client). 

 ```
import { VASTParser } from 'vast-client'

const vastParser = new VASTParser();
```

From VastParser [documentation](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-parser.md#example).

Thows an error

> VastParser is not a constructor

Same with VastClient...

Can you please make sure that it works for you, from clean installation?

**Comment by eliamaino-fp** [comment]
Hi @S4n60w3n, can you provide us some more info about your environment and how you import the library?

Are you doing `import { VASTParser } from 'vast-client'`?

**Comment by S4n60w3n** [comment]
@eliamaino-fp Yes I do, the parsing went wrong.... I will try to create minimal repo

**Comment by S4n60w3n** [comment]
I have prepared [minimal repo](https://github.com/S4n60w3n/vastClient/tree/master) . The issue is little bit different, but still similar enough. 
`...VASTParser is not a constructor`

**Comment by eliamaino-fp** [comment]
Thanks for the repo, I'll take a look into it as soon as possible.

**Comment by eliamaino-fp** [comment]
So it looks like webpack is not using the `module` entrypoint in `package.json` when `browser` and `main` entrypoints are provided too (see https://github.com/webpack/webpack/issues/4674)

According to the thread linked above this PR should fix the issue https://github.com/dailymotion/vast-client-js/pull/243

@S4n60w3n could you try to test that on your side too?

**Comment by S4n60w3n** [comment]
@eliamaino-fp  Seems to be working and minimal repo. Thanks

**Comment by eliamaino-fp** [comment]
Issue fixed in https://github.com/dailymotion/vast-client-js/releases/tag/v2.0.2

**Comment by S4n60w3n** [comment]
@eliamaino-fp Glad, I could help! Thanks for quick issue fix!
