### ISSUE TITLE
Creatives in wrapper get ignored

### ISSUE THREAD

**Issue by CarlosHdez** [dailymotion/vast-client-js#246]
I'm trying to parse a VAST document that has a companion creative and a wrapped one, but whenever I  use `VASTParser` I only get the data for the wrapped one.
It looks roughly like this.
```
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="2.0">
  <Ad id="fakeID">
  <Wrapper>
    <VASTAdTagURI>
      <[CDATA[SOME_URL]>
    </VASTAdTagURI>
    <Creatives>
      <Creative>
        <Linear>
        ...(tracking events)
        </Linear>
      </Creative>
      <Creative>
        <CompanionAds>
          <Companion>
            ... src, tracking and click props
          </Companion>
        </CompanionAds>
      </Creative>
    </Creatives>
  </Wrapper>
  </Ad>
</VAST>
```
Now my problem is that the wrapped XML does not have a companion so when the parser resolves, I only get the result of the wrapped ad but the companion is lost and I get no data on it.
Is this a proper bug or is there another way to use the parser without resolving wrapped elements
I'm using version 2.0.3.
Thanks

**Comment by eliamaino-fp** [comment]
Hi @CarlosHdez, the parser should definitely keep all the creatives at any level.

Can you please provide us the real VAST document you're trying to parse? And if possible attach a small code snippet which shows how you're making the parsing call?

Thanks :)

**Comment by kobawan** [comment]
Hi @CarlosHdez , indeed the companion creatives in wrappers were being ignored and have been fixed in https://github.com/dailymotion/vast-client-js/pull/289 (version 3.0.0-alpha.2)
