### ISSUE TITLE
Add bundlephobia badge with lib size

### ISSUE THREAD

**Issue by jakub-g** [dailymotion/vast-client-js#249]
One of those:

https://badgen.net/#bundlephobia
https://flat.badgen.net/#bundlephobia
https://shields.io/#/examples/size

https://bundlephobia.com/result?p=vast-client
alternatively https://packagephobia.now.sh/result?p=vast-client

**Comment by jakub-g** [comment]
On top of that: https://github.com/siddharthkp/bundlesize to enforce size at PR time :)

**Comment by jakub-g** [comment]
Hmm for some reason bundlephobia can't build `>=2.0.4`
https://bundlephobia.com/result?p=vast-client@2.0.3

it shows `BuildError`
> main.bundle.js from Terser Export statement may only appear at top level [main.bundle.js:23,36600]

**Comment by eliamaino-fp** [comment]
Yes but weird, webpack bundle should use the `module` entry, that means that it should bundle this: https://github.com/dailymotion/vast-client-js/blob/master/dist/vast-client-module.min.js

And there's only one `export` statement (and it's at top level) 🤔
