### ISSUE TITLE
TrackingEvents in Companions

### ISSUE THREAD

**Issue by jtacon** [dailymotion/vast-client-js#251]
Im working with XML files (VAST version 2) that companions have their own TrackingEvents, example:

      <Companion width="300" height="60">
       <HTMLResource>
        <![CDATA[<a href="https://www.example.com" target="_blank">HTML Sample</a>]]>
       </HTMLResource>
       <TrackingEvents>
        <Tracking event='creativeView'><![CDATA[https://example.com/1]]></Tracking>
        <Tracking event='creativeView'><![CDATA[https://example.com/2]]></Tracking>
       </TrackingEvents>
      </Companion>

I don't see that these tracking events are triggered, I work the the 2.0.4 library version.

Do you known if it's something related with the VAST version/XML or I need to make something else to trigger these events?

I also tried to do something with creativeView handler, but without success.

**Comment by eliamaino-fp** [comment]
Hey @jtacon sorry for the late reply.

Yes once you correctly get your VAST parsed using [`VASTClient`](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-client.md) or [`VASTParser`](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-parser.md), you need to use the [`VASTTracker`](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md) to correctly call the tracking urls.

What you want to call are the impression urls, therefore what you need to do is something like this:
```javascript
const tracker = new VASTTracker(null, ad, creative);

tracker.trackImpression(); // This will call the impression urls (the ones having 'creativeView' as event type)
```

Let me know if this helps you to solve the issue :)
