### ISSUE TITLE
Not working with any tags

### ISSUE THREAD

**Issue by PaulMaly** [dailymotion/vast-client-js#252]
Hi, this library really looks like the best VAST library on npm.  And really strange that she doesn't work at all. 

I tried to use it on about 10 VAST tags with the same result - errors on parsing.

Maybe, I'm doing something wrong?

```javascript
var url = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=';

new VAST.VASTClient()
        .get(url) // any VAST
        .then(console.log) // never success
        .catch(console.error); // aways error
```

Quite different errors occurring:

> "Cannot read property 'childNodes' of undefined"

> "Error: XHRURLHandler: at XMLHttpRequest.i.onreadystatechange"

etc.

Also, I've used tags from 4 different platforms and without any success. 

Can anyone help me, please?

**Comment by eliamaino-fp** [comment]
Hey @PaulMaly I can't reproduce any of the listed errors with the [given VAST](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=), the parsing works correctly using the snippet you provided and the [bundled version of the library](https://github.com/dailymotion/vast-client-js/blob/master/dist/vast-client.min.js).

Can you provide me your execution environment and maybe another VAST resource?

**Comment by PaulMaly** [comment]
Hi! Thanks for the answer. Please, check this one:
https://out.pladform.ru/getVast?pl=115560&type=preroll&license=1&thematic=415&age=5&duration=0&target=smarttv&dl=____

**Comment by kobawan** [comment]
Hello, this [vast](https://out.pladform.ru/getVast?pl=115560&type=preroll&license=1&thematic=415&age=5&duration=0&target=smarttv&dl=____) is empty. The parsing doesn't throw any error. Could you recommend another? Also which environment are you using to request the VAST? Are you using browser or node?

**Comment by PaulMaly** [comment]
Hi, @kobawan ! Thanks for the answer! Actually, for me, this vast is not empty. Seems it has some restriction for the region. Sorry about that. 

Can you check [this one ](https://an.yandex.ru/meta/322767?imp-id=1&charset=UTF-8&target-ref=http%3A%2F%2Fvintera.tv&rnd=123456789), please!

**Comment by PaulMaly** [comment]
Seems all tags geo-restricted ((( 

The last interesting thing I found, this VAST:

```xml
<VAST version="3.0">
  <Ad id="986">...</Ad>
  <Ad id="1020">...</Ad>
</VAST>
```
parsing as empty `ads` array. Is in correct?
