### ISSUE TITLE
VASTTracker not triggering multiple tracking events

### ISSUE THREAD

**Issue by offnertho** [dailymotion/vast-client-js#254]
I am using the VASTTracker for tracking of an linear ad.

More concrete I implemented the following code based on your example: 
```
player.addEventListener('volumechange', e => {
  vastTracker.setMuted(e.target.muted);
});
```

However, if I switch between mute/unmute, I do experience that the corresponding TrackingURL is not always requested. After debugging I found that sometimes the network request is not issued at all (i.e does not even appear in the network tab), when the same TrackingURL is used. This can be reproduced with the following VAST tags: `https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=`

If I manipulate the trackingURL (for example by adding a `&[RANDOM]` parameter), the TrackingURL always gets called.

This is reproducable in Chrome and Firefox.

**Comment by eliamaino-fp** [comment]
Hey @offnertho thanks for opening this, we'll look into it ASAP :)

**Comment by eliamaino-fp** [comment]
Are you sure you're passing a different value for the `muted` property every time you call `setMuted`? I mean, the track URLs are not called if there's no change in the muted status:
https://github.com/dailymotion/vast-client-js/blob/32efd4303e1b69ba78e7b29cf67743dc70cf9bed/src/vast_tracker.js#L188-L193

Anyway it's weird that it works by appending something to the tracking URL 🤔

**Comment by offnertho** [comment]
Yes, I always pass a different mute state. This is also reproducable with other state changes.
