### ISSUE TITLE
Load vast tag from XML string is not working in version 2 

### ISSUE THREAD

**Issue by ddiukariev** [dailymotion/vast-client-js#256]
Vast client versions below 2 allowed to specify either url to a vast tag or xml string (via options.response). Since version 2 this is no longer possible and it is not listed in breaking changes. Are there any plans on implementing this?

**Comment by eliamaino-fp** [comment]
Hi @ddiukariev , it's still possible to directly parse an XML by using the `VASTParser`, see https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-parser.md#parsevastvastxml-options

To make more clear the difference between the `VASTClient` and `VASTParser` we tried to push the first to be used mostly when requesting a sequence of VAST resources, while the second should be mainly used to parse single resources.

I'll update the migration guide anyway to make this more clear, thanks.
