### ISSUE TITLE
dist/vast-client.js misnamed xhr function

### ISSUE THREAD

**Issue by Paradam** [dailymotion/vast-client-js#269]
We've discovered an issue with the compiled vast-client.js file where creating an XHR object at line 1687 which refers to an undefined function "_xhr2()"

Expected Result
`var _xhr2 = xhr();`
Ads are requested.

Actual Result
undefined is not a function and no ads play or are requested.

Tested using latest 2.2.0 from npm.

**Comment by eliamaino-fp** [comment]
Hi @Paradam , thanks for spotting this. A fix is on the way and will be released soon https://github.com/dailymotion/vast-client-js/pull/270

**Comment by eliamaino-fp** [comment]
Fix was released in https://github.com/dailymotion/vast-client-js/releases/tag/2.2.1, should be ok now. Please @Paradam let us know if you still encounter the bug.

**Comment by Paradam** [comment]
@eliamaino-fp The update is working for us now.
Thanks.
