### ISSUE TITLE
Road to a 3.0 release

### ISSUE THREAD

**Issue by eliamaino-fp** [dailymotion/vast-client-js#272]
Here's a personal list of changes/features/improvements I'd like to add to a future `3.0` release:

- VAST 4.0 support (and 4.1 actually)
   - See https://github.com/dailymotion/vast-client-js/issues/98
- New unit test structure and framework
   - See https://github.com/dailymotion/vast-client-js/issues/264
   - See https://github.com/dailymotion/vast-client-js/issues/278
- Return more information (even if parsing fails at some point)
- Reduce bundle size 
   - Simple Objects over classes?
   - More performant parsing?
   - Use custom event emitter instead of node class?

**Comment by eliamaino-fp** [comment]
https://github.com/dailymotion/vast-client-js/milestone/1

**Comment by unglud** [comment]
Is VAST 4.1 already in the release 3.0 or still in development?
If not, expect many PR from us soon )

**Comment by eliamaino-fp** [comment]
Hi @unglud :)

VAST 4.0 and 4.1 spec support are part of the roadmap for the upcoming 3.0 version but we haven't directly started to work on them, so of course any help wpuld be more than welcome.

If you decide to start some work on that, please remind that the library needs to remain retro-compatibile with VAST 3.0 and 2.0. Therefore any modification should not break the existing APIs.

We're already working on a 3.0 branch https://github.com/dailymotion/vast-client-js/tree/3.0-version and already shipped some alpha versions https://github.com/dailymotion/vast-client-js/releases.
You can checkout this branch to start any further development.

Feel free to ask any questions and thanks in advance for you help 😃

**Comment by unglud** [comment]
Would it be ok for this release introduce only partial support of VAST 4.1? Cuz currently we are ready with Mezzanine, Viewability, Standardized Timestamp and additional tracking events. There is not much more left after this but we will work on leftovers only in 2-3 months.

Or 3.0.0 will not be released without official 4.1 support? In this case, we will use our fork with partial support until it will be officially supported.

Thanks!

**Comment by eliamaino-fp** [comment]
Ideally we'd like to have a full support in the final `3.0` release.

But we try to release alpha and beta versions as soon as a set of features is developed. Maybe we could implement what you have till now and release it as an aplha on npm, so you can install and test it on your your side easily.

What do you think?

**Comment by unglud** [comment]
Couldn't be better! Thank you!

**Comment by unglud** [comment]
I think I also add mezzanine support

**Comment by kobawan** [comment]
I believe all issues/PR's are created for 3.0 roadmap:
- 4.1 support: #324 , #323 , #322 , #321 , #320 , #319 , #318 , #316 
- unit tests improvement: #264 , pr https://github.com/dailymotion/vast-client-js/pull/313
- more information: pr https://github.com/dailymotion/vast-client-js/pull/307
- performance: #317, #249, pr https://github.com/dailymotion/vast-client-js/pull/274 (merged)

Once these issues/PR's have been addressed, I believe we will be able to release version 3.0

**Comment by ZacharieTFR** [comment]
Hello, 

Version 3.0 is [officially released](https://github.com/dailymotion/vast-client-js/releases/tag/3.0.0)! 🎉
