### ISSUE TITLE
Refactoring unit tests away from mocha. Jest VS Jasmine?

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#278]
Current tests are in Mocha, and they require third-party libraries. The syntax is also different from Jest and Jasmine. Based on this, we should migrate to another testing framework.

Top current testing frameworks are Jest and Jasmine. Which one would be better for this project?

Pros Jest:
* Parallel test execution
* Constant support and maintenance by Facebook

Pros Jasmine:
* Big community
* Matured framework

**Comment by eliamaino-fp** [comment]
We can give a try to Jest 👍

**Comment by kobawan** [comment]
My personal preference is Jest because of the speed, and it supports DOM testing (which is needed for testing XML documents)

**Comment by eliamaino-fp** [comment]
Support for Jest added in https://github.com/dailymotion/vast-client-js/pull/279, going to be released as part of the 3.0 version of the library.
