### ISSUE TITLE
Skip deletes all tracking possibilities

### ISSUE THREAD

**Issue by manny42** [dailymotion/vast-client-js#281]
I am trying to track closing an ad after the skip button has been called.
The situation is we use a companionAd as an EndCard, thus we still need the user to click on a close button to dismiss it.

But in the tracker, this line cause the call to close tracking to not call the tracking urls.
Is this normal behavior? And if yes, why?

https://github.com/dailymotion/vast-client-js/blob/586620c7693ab701e97b9bc53064bca0eccacdc5/src/vast_tracker.js#L350

**Comment by kobawan** [comment]
Hello @manny42 !

It seems that this line is part of the legacy code and can be removed, since it is not being used on any other tracking events. Could you please create a PR to delete it?

**Comment by manny42** [comment]
Hey @kobawan

It seems like I don't have the right to push to the repo on the branch I created: `remove-skip-deletion-of-event-tracking`

Also should I PR to 3.0-version or to master?

**Comment by kobawan** [comment]
Hello @manny42 ,
This is a public repo so you should have the rights to push your changes to your branch.
Did you fork the repo or clone it using https?
You can follow these steps on how to [contribute](https://github.com/dailymotion/vast-client-js/blob/master/docs/CONTRIBUTING.md) to vast-client-js.
Please target master in your PR :)

**Comment by manny42** [comment]
I don't get it, I can't push to the repo.
I have it cloned with ssh, have the right remote.
I've tried renaming the branch, using the terminal, github client, ssh to GitHub with my key everything is OK. Re-cloned the repo with ssh and did it again, still not working.
I guess I'm not allowed in public anymore 😆

**Comment by eliamaino-fp** [comment]
Hey @manny42, maybe try to fork the repo and open a PR from there? 🤔 😅

**Comment by eliamaino-fp** [comment]
Anyway, let me know if you manage to open the PR, otherwise I can do it for you ;) And since it's a bug let's point it to master 🚢

**Comment by manny42** [comment]
Managed to do it by forking and creating PR. Linked the PR to the issue! Thanks for the help! 😄

**Comment by eliamaino-fp** [comment]
Fixed in https://github.com/dailymotion/vast-client-js/releases/tag/2.2.4
