### ISSUE TITLE
Allow parsing of VAST without resolving wrappers

### ISSUE THREAD

**Issue by bwallberg** [dailymotion/vast-client-js#285]
When using the VASTParser resolving any wrappers directly might not be desired by a developer ( eg. when working with Chromecast CAF SDK where all AD Ids needs to be provided at the start of content playback ), currently this is not really possible, we can set `resolveAll` to `false` however this will still result in the first AdPod to resolve it's wrappers.

My suggestion is to simply split the XML parsing in `parse()` into a `parseXML()` method ( see PR https://github.com/dailymotion/vast-client-js/pull/284 ) this allows user to handle that themselves and introduces no changes to the API of the library.

**Comment by eliamaino-fp** [comment]
Released in https://github.com/dailymotion/vast-client-js/releases/tag/2.4.0
