### ISSUE TITLE
[Question] VAST-Tracker, `macro2` intention?

### ISSUE THREAD

**Issue by bwallberg** [dailymotion/vast-client-js#288]
In https://github.com/dailymotion/vast-client-js/blob/master/src/util/util.js you have the following code

```
 for (const key in variables) {
      const value = variables[key];
      const macro1 = `[${key}]`;
      const macro2 = `%%${key}%%`;
      resolveURL = resolveURL.replace(macro1, value);
      resolveURL = resolveURL.replace(macro2, value);
}
```

What is the intention of `macro2`? I'm guessing it's to to replace the `[]` characters if they are encoded? In which case I think there is a bug here because the `[` is encoded to `%5B` and `]` is encoded to `%5D`.

**Comment by bwallberg** [comment]
Let me know if it's a bug and I'll create a PR :)

**Comment by rumesh** [comment]
Hello @bwallberg , it's not a bug but a feature 😄 
In fact macro can be like ```[VALUE_TO_REPLACE]``` or ```%%VALUE_TO_REPLACE%%```.
It's to manage this 2 different form of macro we have this case.

As example sometime you have this:
https://www.example.com/tracking?pram1=test&param2=test2&ts=[TIMESTAMP]
you can also have it like this:
https://www.example.com/tracking?pram1=test&param2=test2&ts=%%TIMESTAMP%%

**Comment by bwallberg** [comment]
@rumesh ah I see, thank you!
I think our adprovider is incorrectly encoding the `[]`characters -_-. Thanks for the answer :)
