### ISSUE TITLE
getRemainingAds(true) question/proposal

### ISSUE THREAD

**Issue by mysuf** [dailymotion/vast-client-js#294]
Hi,

I have two questions about `vastParser.getRemainingAds(true)`:

1. why is array remainingAds flattened? Then original structure of groups/pods is lost. "getRemainingAds" is plural so I would expect array of VastResponses as returned value with either one item or all remaining items. I mean something like this:

```javascript
  // @return {Promise([...VastResponse])}
  getRemainingAds(all) {
    if (this.remainingAds.length === 0) {
      return Promise.reject(
        new Error('No more ads are available for the given VAST')
      );
    }

    const adGroups = all
      // slice dumps remainingAds and returns dumped items
      ? this.remainingAds.splice(0, this.remainingAds.length)
      : this.remainingAds.shift();
    this.errorURLTemplates = [];
    this.parentURLs = [];

    // or Promise.all instead of syncing reduce.
    return adGroups.reduce((getPrevious, ads) => {
      return getPrevious.then(group => {
        return this.resolveAds(ads, {
          wrapperDepth: 0,
          originalUrl: this.rootURL
        }).then(resolvedAds => {
          group.push(this.buildVASTResponse(resolvedAds));
          return group;
        })
      });
    }, Promise.resolve([]));
  }
```
2. why are `vastParser.remainingAds` not emptied when `all===true`?

Thanks

**Comment by kobawan** [comment]
Hi @mysuf , sorry for the late reply. The questions are a bit tricky. 

I can't really answer for the first question, but in my opinion remaining ads are flattened for simplicity and probably to not introduce breaking changes. 

In regards to the second question I think the answer relies in `resolveAds` [here](https://github.com/dailymotion/vast-client-js/blob/master/src/parser/vast_parser.js#L365). It only clears `this.remainingAds` on resolving the ads.

If you wish to introduce changes from the first question feel free to contribute following our [guidelines.](https://github.com/dailymotion/vast-client-js/blob/master/docs/CONTRIBUTING.md#pull-requests) I hope my answers are helpful :)

**Comment by mysuf** [comment]
Thank you.
