### ISSUE TITLE
get() new Error change message

### ISSUE THREAD

**Issue by mih4lev** [dailymotion/vast-client-js#300]
Hello! Big thanks for this library ;)

I have 1 question about 

```
function get(url, options, cb) {
... cb(new Error(`XHRURLHandler: ${request.statusText}`));
}
```

May be can add request.status to this message for more info?

```
function get(url, options, cb) {
... cb(new Error(`XHRURLHandler: ${request.status} ${request.statusText}`));
}
```

Thanks!

**Comment by kobawan** [comment]
Hi! Sure it can be added, feel free to open a PR with the change and it will be reviewed and merged. You can read about our contributing guidelines [here](https://github.com/dailymotion/vast-client-js/blob/master/docs/CONTRIBUTING.md#pull-requests) :)

**Comment by kobawan** [comment]
I added a more descriptive message in scope of https://github.com/dailymotion/vast-client-js/pull/332 .
