### ISSUE TITLE
Error thrown with Webview 33

### ISSUE THREAD

**Issue by manny42** [dailymotion/vast-client-js#306]
I don't know if this is a requirement for the library but there is an issue when you try to parse an XML document with the latest version of the library there is an issue because `Object.assign` does not exists in ES6 implementation of Webview 33 that is shipped with versions 4.4.3 and 4.4.4 of android.

I am looking into it right now, but would like to know if you had an idea or if it was something you don't want to support in which case I'll fork.

**Comment by kobawan** [comment]
Hi!
We aim to support as many devices as possible, and in fact we should have polyfills for this. If you wish to speed up the process, you can contribute to the repo and we will review your PR :)

**Comment by manny42** [comment]
Hi!

So I've been trying to get this to work and it seems like I'm missing something...

I changed the babelPlugin config in rollup.config.js and it looks like this:

```
const babelPlugin = babel({
  babelrc: false,
  presets: [['@babel/preset-env', {
    modules: false,
    useBuiltIns: 'usage',
    targets: "android >= 4.4.2 or ios >= 9",
  }]],
  exclude: ['node_modules/**']
});
```

The output is promising:

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
core-js/modules/web.dom.iterable (imported by src/parser/vast_parser.js, src/util/storage.js, src/ad_extension.js)
core-js/modules/es6.array.iterator (imported by src/parser/vast_parser.js, src/util/storage.js, src/ad_extension.js)
core-js/modules/es6.string.iterator (imported by src/parser/vast_parser.js)
core-js/modules/es6.promise (imported by src/parser/vast_parser.js, src/vast_client.js)
core-js/modules/es6.object.to-string (imported by src/parser/vast_parser.js, src/vast_client.js, src/util/util.js, src/util/storage.js, src/ad_extension.js)
core-js/modules/es6.object.assign (imported by src/parser/vast_parser.js, src/vast_client.js)
core-js/modules/es6.regexp.split (imported by src/parser/parser_utils.js)
core-js/modules/es6.regexp.replace (imported by src/util/util.js)
core-js/modules/es6.regexp.to-string (imported by src/util/util.js)
core-js/modules/es6.object.keys (imported by src/util/storage.js, src/ad_extension.js)
created dist/vast-client.js in 2.7s
```

But it seems like the polyfill for `assign` is not inserted within the output file. Am I missing something?

**Comment by manny42** [comment]
After reading about people's experience with this I found out that I was missing modules to handle all those polyfills.

So I added `  plugins: ['transform-object-assign'],` to the `babelPlugin` config. But that means we need to import a different module for each polyfill we require. Isn't that a bit much?

**Comment by kobawan** [comment]
I'm not sure I understood the last part:

> But that means we need to import a different module for each polyfill we require

Can you clarify? I assumed the plugin setup would be shared between all modules.
Another problem is that we are trying to keep our bundle size small, and depending on the plugin it might increase bundle size significantly. If the bundle size difference is large and you definitely need support for these device versions, I recommend instead adding the polyfill to your own application.

**Comment by ZacharieTFR** [comment]
Hello, I’m closing this issue because it has been inactive for a year.

Please reopen if you still encounter this issue with the latest version: https://github.com/dailymotion/vast-client-js/releases/ 😉

Thank you!
