### ISSUE TITLE
VastParser#trackErrorEvent() mutates DEFAULT_EVENT_DATA

### ISSUE THREAD

**Issue by mseeley** [dailymotion/vast-client-js#309]
Hi DM humans 👋:)

Reading through the source I found the following usage of `Object.assign`:

https://github.com/dailymotion/vast-client-js/blob/19223a0e4c685eb259239524f46f5e89b47b4eda/src/parser/vast_parser.js#L80-L86

`Object.assign` will transform then return the first argument, in this case `DEFAULT_EVENT_DATA`.

The current approach is only safe if the `data` argument has a fixed interface. Usages of `trackErrorEvent` in the parser provider different `data` shapes. So, if `trackErrorEvent` is called twice then the second call can contain data from the first call. It may not be typical for a parser to emit multiple errors but it looks like a parser instance can be long lived and asked to `parse` multiple `vastXml` objects.

Anyway, easy fix is to provider an empty object as the first param `Object.assign({}, ...` or shift to a spread syntax.

The same behavior is also present in `VastClient`:

https://github.com/dailymotion/vast-client-js/blob/707e854d6213dd9580c22a08a7e694f3923c723d/src/vast_client.js#L95

I think it would be unexpected for `get(url, optionsA)` to change `this.defaultOptions` such that `get(url, optionsB)` winds up using a mix of `defaultOptions`, `optionsA`, and `optionsB`.

**Comment by mseeley** [comment]
If it's helpful, here's [a CodePen](https://codepen.io/mseeley/pen/aboawXL) that demonstrates the underlying issue.

**Comment by kobawan** [comment]
Hi, you're definitely right, we are mutating `DEFAULT_EVENT_DATA` and `this.defaultOptions`. Using spread syntax would be quite alright as a fix. Would you be interested in contributing to our amazing vast-client? If so, please follow our [contributing guidelines](https://github.com/dailymotion/vast-client-js/blob/master/docs/CONTRIBUTING.md). Great job in spotting this :)

**Comment by mseeley** [comment]
Hi @kobawan, sure thing. I'm happy to.
