### ISSUE TITLE
Implement missing VAST 4.1 trackers

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#316]
According to IAB specs for [VAST 4.1](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf) our vast-client is missing the following trackers:

**Linear and NonLinear Ads Metrics**
- [x] notUsed: This ad was not and will not be played (e.g. it was prefetched for a particular
ad break but was not chosen for playback). This allows ad servers to reuse an ad earlier
than otherwise would be possible due to budget/frequency capping. This is a terminal event; no other tracking events should be sent when this is used. Player support is
optional and if implemented is provided on a best effort basis as it is not technically
possible to fire this event for every unused ad (e.g. when the player itself is terminated
before playback).
- [x] otherAdInteraction: An optional metric that can capture all other user interactions
under one metric such as hover-overs, or custom clicks. It should NOT replace
clickthrough events or other existing events like mute, unmute, pause, etc.

**NonLinear Ads Metrics**
- [x] acceptInvitation: The user clicked or otherwise activated a control used to pause
streaming content, which either expands the ad within the player’s viewable area or
“takes-over” the streaming content area by launching an additional portion of the ad. An ad in video format ad is usually played upon acceptance, but other forms of
media such as games, animation, tutorials, social media, or other engaging media
are also used.
- [x] adExpand: The user activated a control to expand the creative.
- [x] adCollapse: The user activated a control to reduce the creative to its original
dimensions. 
- [x] minimize: The user clicked or otherwise activated a control used to minimize the ad
to a size smaller than a collapsed ad but without fully dispatching the ad from the
player environment. Unlike a collapsed ad that is big enough to display it’s message,
the minimized ad is only big enough to offer a control that enables the user to
redisplay the ad if desired.
- [x] overlayViewDuration: The time that the initial ad is displayed. This time is based on
the time between the impression and either the completed length of display based
on the agreement between transactional parties or a close, minimize, or accept
invitation event.

These events should be implemented in vast-tracker class. All info is in specs mentioned at the top.
Development should be done based from branch 3.0-version.

**Comment by ZacharieTFR** [comment]
I'm on it ! 🏃
