### ISSUE TITLE
[VAST 4.1] Implement missing sub elements of AdVerification

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#318]
Currently,  Verification element is missing parsing of the following sub elements:
- [x] ExecutableResource: 
       - required attributes: apiFramework, type
       - value: CDATA-wrapped value
- [x] TrackingEvents:
       - subElement: Tracking **

** Tracking:
- value: CDATA-wrapped URI
- required attributes: event (for now only "verificationNotExecuted")

For more info on specs, see page 75 of [IAB VAST 4.1 specs](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf).
Parsing of Ad Verifications is currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/ad_parser.js#L322
Development should be done based from branch 3.0-version.

**Comment by rgulrajani** [comment]
working on it

**Comment by kobawan** [comment]
@rgulrajani here (page 78):
<img width="714" alt="Screenshot 2019-10-11 at 10 57 22" src="https://user-images.githubusercontent.com/9026911/66638830-ffb48600-ec15-11e9-9a7d-a1fc1c5381f6.png">
