### ISSUE TITLE
[VAST 4.1] Implement missing attributes for Companion ads and Icons

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#319]
According to IAB 4.1 specs, our parser is missing the following attributes in:
- Companion ad:
- [x] pxratio - The pixel ratio for which the companion creative is intended. The pixel ratio is the ratio of physical pixels on the device to the device-independent pixels. An ad intended
for display on a device with a pixel ratio that is twice that of a standard 1:1 pixel ratio
would use the value "2." Default value is "1."
- [x] renderingMode - Used to indicate when and where to use this companion ad. Values can be “default” or “end-card” or “concurrent”. If this field is empty or not given, “default” will be used.

For more info on specs, see page 67 of IAB [VAST 4.1 specs](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf).
Parsing of companion ads is currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/creative_companion_parser.js#L22

- Icon:
- [x] pxratio - The pixel ratio for which the icon creative is intended. The pixel ratio is the ratio of
physical pixels on the device to the device-independent pixels. An ad intended for
display on a device with a pixel ratio that is twice that of a standard 1:1 pixel ratio
would use the value "2." Default value is "1."

For more info on specs, see page 60 of IAB [VAST 4.1 specs](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf).
Parsing of icons is currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/creative_linear_parser.js#L198

Development should be done based from branch 3.0-version.

**Comment by rgulrajani** [comment]
Working on it

**Comment by kobawan** [comment]
fixed!
