### ISSUE TITLE
[VAST 4.1] Implement missing attributes and sub elements for MediaFile

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#320]
According to IAB 4.1 specs, our parser is missing the following in the MediaFile element:
- attributes:
- [x] fileSize - Optional field that helps eliminate the need to calculate the size based on bitrate
and duration. Units - Bytes
- [x] mediaType - Type of media file (2D / 3D / 360 / etc). Optional. Default value = 2D

- sub elements:
- [x] InteractiveCreativeFile:
       - value: CDATA-wrapped URI
       - attributes: type, apiFramework, variableDuration
- [x] ClosedCaptionFiles
       - sub elements: ClosedCaptionFile **

** ClosedCaptionFile:
       - value: CDATA-wrapped URI
       - attributes: type, language

For more info on specs, see page 52 of IAB [VAST 4.1 specs](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf).
Parsing of media files are currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/creative_linear_parser.js#L113
Development should be done based from branch 3.0-version.

**Comment by rgulrajani** [comment]
working on it
