### ISSUE TITLE
[VAST 4.1] Implement missing sub elements for Creative

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#321]
According to IAB 4.1 specs, our parser is missing the sub elements for the Creative element:
- [x] UniversalAdId:
       - value: A string identifying the unique creative identifier. Default value is “unknown”
       - required attributes: idRegistry
- [x] CreativeExtensions
       - sub elements: CreativeExtension **

** CreativeExtension:
       - value: Custom XML object
       - attributes: type

For more info on specs, see page 48 of IAB [VAST 4.1 specs](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf).
Parsing of creatives are currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/ad_parser.js#L64
Development should be done based from branch 3.0-version.

**Comment by rgulrajani** [comment]
Working on it
