### ISSUE TITLE
[VAST 4.1] Implement missing attributes and sub elements of Wrapper

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#322]
According to IAB 4.1 specs, our parser is missing the following for the Wrapper element:
Attributes:
- [ ] followAdditionalWrappers - a Boolean value that identifies whether subsequent Wrappers after a
requested VAST response is allowed. If false, any Wrappers received (i.e. not
an Inline VAST response) should be ignored. Otherwise, VAST Wrappers
received should be accepted (default value is “true.”)
- [ ] allowMultipleAds - a Boolean value that identifies whether multiple ads are allowed in the
requested VAST response. If true, both Pods and stand-alone ads are allowed.
If false, only the first stand-alone Ad (with no sequence values) in the
requested VAST response is allowed. Default value is “false.”
- [ ] fallbackOnNoAd - a Boolean value that provides instruction for using an available Ad when the
requested VAST response returns no ads. If true, the media player should
select from any stand-alone ads available. If false and the Wrapper represents
an Ad in a Pod, the media player should move on to the next Ad in a Pod;
otherwise, the media player can follow through at its own discretion where
no-ad responses are concerned.

Sub Elements:
- [ ] BlockedAdCategories:
- value: A string that provides comma separated list of category codes or labels per
authority that identify the ad content. 
- required attributes: authority

New attributes should be parsed and implemented according to their description.
For more info on specs, see page 82 of IAB VAST 4.1 specs.
Parsing of wrapper is currently being done in https://github.com/dailymotion/vast-client-js/blob/3.0-version/src/parser/ad_parser.js#L164
Development should be done based from branch 3.0-version.

**Comment by florianorpeliere** [comment]
Hey !
I will try to working on it 😸

**Comment by rumesh** [comment]
@florianorpeliere will you have any time to work on this ?
