### ISSUE TITLE
Add id attribute to missing elements

### ISSUE THREAD

**Issue by kobawan** [dailymotion/vast-client-js#324]
Currently, the id attribute of some elements are being ignored during parsing. They are the following:
- [x] impressionURLTemplates ids
- [x] advertiser id
- [x] companionClickTrackingURLTemplates ids
- [x] iconClickTrackingURLTemplates ids
- [x] nonlinearClickTrackingURLTemplates ids
- [x] videoClickThroughURLTemplate id
- [x] videoClickTrackingURLTemplates ids
- [x] videoCustomClickURLTemplates ids

The structure for arrays containing urls should be changed to, for example:
```
videoClickTrackingURLTemplates = [
  {
    url : 'http://example.com/linear-clicktracking1',
    id : 'id1'
  },
  {
    url : 'http://example.com/linear-clicktracking2',
    id : 'id2'
  }
];
```

For more info see https://github.com/dailymotion/vast-client-js/issues/131
VAST specs: https://iabtechlab.com/wp-content/uploads/2019/06/VAST_4.2_final_june26.pdf
Development should be done based from branch 3.0-version.

**Comment by rgulrajani** [comment]
Working on it.
