### ISSUE TITLE
Set headers

### ISSUE THREAD

**Issue by TinchoF** [dailymotion/vast-client-js#344]
Is there any way to set headers in the getAndParseVAST function or get function to fetch when the "User-Agent" is required?

**Comment by kobawan** [comment]
Hello @TinchoF , with the default url handler functions it is not possible, but you can provide a custom function for fetching. `getAndParseVAST` and `get` functions only pass the options `timeout` and `withCredentials` to the default url handlers.

**Comment by ZacharieTFR** [comment]
Hello, I’m closing this issue because it has been inactive for nearly a year.
Please reopen if you still have issue to provide a custom function for fetching 😉 
Thank you!

**Comment by fabiiomariiano** [comment]
> Hello @TinchoF , with the default url handler functions it is not possible, but you can provide a custom function for fetching. `getAndParseVAST` and `get` functions only pass the options `timeout` and `withCredentials` to the default url handlers.

Thanks! This worked for me. 

Using some like this:

```
vastClient.get(vastUrl, {
    urlHandler: {
      get: function get(url, options, cb) {
        return getXhrWithCredential(url, options, cb, credential);
      }
    }
  })
```

and providing my custom get in getXhrWithCredential, where I add the header with the received credential.
