### ISSUE TITLE
Any plans to adding daast?

### ISSUE THREAD

**Issue by maxbaluev** [dailymotion/vast-client-js#348]

**Comment by ZacharieTFR** [comment]
Hi @maxbaluev  !

DAAST has been merged into VAST 4.1.
We will soon release a stable version of vast-client supporting vast 4.1 and therefore audio ad.
You can already use the 3.0-version alpha which support VAST 4.1 (keep in mind it's an alpha version).

For more information about it please see page 17 of VAST 4.1 specs https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf

**Comment by ZacharieTFR** [comment]
Hello,
Version 3.0 is officially released! 🎉 It is therefore no longer necessary to use alpha versions.
