### ISSUE TITLE
[Bug] Infinite fetching loop with VASTParser

### ISSUE THREAD

**Issue by conradolk** [dailymotion/vast-client-js#350]
I'm using `VASTParser.parseVAST(XMLObject)`, and it's working nicely, XMLObject is this XML tag transformed into an object, but the library keeps fetching the URL under the VASTAdTagURI attribute (`https://vast.adsafeprotected.com/vast/fwjsvid/st/275293/35611685/skeleton.js?includeFlash=false&originalVast=https://tad.clickitnow.net/ddm/pfadx/N9166.1593590MOBSTA.CO.UK/B22633460.246126690;sz=0x0;ord={$timestamp$};dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER]`) over and over, in a never ending loop. Here is the tag that I'm using:

`<VAST version='2.0'
	xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='oxml.xsd'>
	<Ad id='{$CRID$}'>
		<Wrapper>
			<AdSystem version='1.0'>Test</AdSystem>
			<VASTAdTagURI>
				<![CDATA[https://vast.adsafeprotected.com/vast/fwjsvid/st/275293/35611685/skeleton.js?includeFlash=false&originalVast=https://tad.clickitnow.net/ddm/pfadx/N9166.1593590MOBSTA.CO.UK/B22633460.246126690;sz=0x0;ord={$timestamp$};dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER]]]>
			</VASTAdTagURI>
			<Impression>
				<![CDATA[{$IMPRESSION_TRACK_URL$}]]>
			</Impression>
			<Creatives>
				<Creative AdID='1'>
					<Linear>
						<TrackingEvents>
							<Tracking event="start">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/start?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
							<Tracking event="firstQuartile">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/firstQuartile?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
							<Tracking event="midpoint">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/midpoint?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
							<Tracking event="thirdQuartile">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/thirdQuartile?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
							<Tracking event="complete">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/complete?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
							<Tracking event="skip">
								<![CDATA[https://geo-tracker.test.com/hyperad/tracking/action/skip?click_id={$BID_DIGEST$}&crid={$CRID$}]]>
							</Tracking>
						</TrackingEvents>
						<VideoClicks>
							<ClickTracking>
								<![CDATA[{$CLICK_TRACK_URL$}]]>
							</ClickTracking>
						</VideoClicks>
					</Linear>
				</Creative>
				<Creative AdID="{$CRID$}-Companion"></Creative>
			</Creatives>
		</Wrapper>
	</Ad>
</VAST>`

¿Any ideas of what the problem might be?

Thanks for the great library.

**Comment by ZacharieTFR** [comment]
Hello @conradolk !

Which version of vast-client are you using ? 

I checked the vast that you've provided, the `VASTAdTagURI` redirect to another wrapper which `VASTAdTagURI` redirect to:
`https://tad.clickitnow.net/ddm/pfadx/N9166.1593590MOBSTA.CO.UK/B22633460.246126690;sz=0x0;ord={$timestamp$};dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER]`. 
In the 3.0-version, this last redirection end on timeout which produces a `ERRORCODE 301` (Timeout of VAST URI provided in Wrapper element).

Furthermore the last element `Creative` shouldn't be empty as specified by iab 
https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf#page=89

**Comment by conradolk** [comment]
¡Hi! thanks for replying.

I'm using the 3.0 version. This is the real VAST tag that I'm using (I modified the one above for company reasons), but since I can't seem to make it work, I'll post it:

`<VAST version='2.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='oxml.xsd'> <Ad id='{$CRID$}'> <Wrapper> <AdSystem version='1.0'>Smadex</AdSystem> <VASTAdTagURI> <![CDATA[https://vast.adsafeprotected.com/vast/fwjsvid/st/275293/35611684/skeleton.js?includeFlash=false&originalVast=https://ad.doubleclick.net/ddm/pfadx/N9166.1593590MOBSTA.CO.UK/B22633460.246126687;sz=0x0;ord={$timestamp$};dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER]]]> </VASTAdTagURI> <Impression> <![CDATA[{$IMPRESSION_TRACK_URL$}]]> </Impression> <Creatives> <Creative AdID='1'> <Linear> <TrackingEvents> <Tracking event="start"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/start?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> <Tracking event="firstQuartile"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/firstQuartile?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> <Tracking event="midpoint"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/midpoint?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> <Tracking event="thirdQuartile"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/thirdQuartile?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> <Tracking event="complete"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/complete?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> <Tracking event="skip"> <![CDATA[https://geo-tracker.smadex.com/hyperad/tracking/action/skip?click_id={$BID_DIGEST$}&crid={$CRID$}]]> </Tracking> </TrackingEvents> <VideoClicks> <ClickTracking> <![CDATA[{$CLICK_TRACK_URL$}]]> </ClickTracking> </VideoClicks> </Linear> </Creative> <Creative AdID="{$CRID$}-Companion"></Creative> </Creatives> </Wrapper> </Ad> </VAST>`

I get infinite request loop to `https://vast.adsafeprotected.com/vast/fwjsvid/st/275293/35611684/skeleton.js?includeFlash=false&originalVast=https://ad.doubleclick.net/ddm/pfadx/N9166.1593590MOBSTA.CO.UK/B22633460.246126687;sz=0x0;ord={$timestamp$};dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;dcmt=text/xml;dc_sdk_apis=[APIFRAMEWORKS];dc_omid_p=[OMIDPARTNER]`

There is no timeout this time, the tag is actually being parsed correctly, but it keeps going.

**Comment by ZacharieTFR** [comment]
Indeed with this VAST there is no more timeout and it work as expected but I still can't reproduce the bug. What do you mean exactly by infinite request loop ? If you open the developper tools of your browser in the panel network you see multiple request with the same url and new ones that are still being added?

**Comment by conradolk** [comment]
It turns out that it was some completely unrelated, some Angular HTML template thing.. for some reason it was triggering infinite VAST requests even though it was not associated with the VAST generation. I guess it was some JavaScript related thing that I don't have to time debug haha. 

Thank you for your time!
