### ISSUE TITLE
Can Vpaid ads be played by this lib?

### ISSUE THREAD

**Issue by TunayNovruz** [dailymotion/vast-client-js#353]

**Comment by ZacharieTFR** [comment]
Hi @TunayNovruz,
No, the vast-client will not play the ad by itself. This lib is used to fetch and parse VAST documents.
The vast-client provides three components:
- A VAST Client to fetch and parse VAST XML resources into JavaScript Objects.
- A VAST Parser to directly parse a VAST XML.
- A VAST Tracker to batch and call tracking URLs.

As the vast-client is fully compliant with VPAID, all xml elements of VPAID will be parsed but you will have to implement the use of VPAID on your player by yourself. Please see issue https://github.com/dailymotion/vast-client-js/issues/196 for more details

**Comment by TunayNovruz** [comment]
Thanks
