### ISSUE TITLE
Error in JEST Tests: VastParser.getAndParseVAST "Please bundle the library for node to use the node urlHandler"

### ISSUE THREAD

**Issue by Doca** [dailymotion/vast-client-js#372]
Hi I'm currently developing my wrapper around your library and want to write JEST tests. JEST also uses node to run the tests and I wonder if you have an easy way to overcome the error: "Please bundle the library for node to use the node urlHandler."

In my tests I use the library installed with npm.
Any thoughts on this?

**Comment by ZacharieTFR** [comment]
Hello @Doca, which version of vast-client are you using ?

**Comment by superxcgm** [comment]
I encountered the same problem. I'm using vast-client 3.0.0(5cf631b).

**Comment by ZacharieTFR** [comment]
Hello, the issue has been fixed in the latest release: [3.1.1](https://github.com/dailymotion/vast-client-js/releases/tag/3.1.1). 
Can you do the update and tell me if you still have the error ?

**Comment by ZacharieTFR** [comment]
Hello, I'm closing this issue because it has been inactive for nearly a year and half.
Please reopen it if you still encounter some issues.
