### ISSUE TITLE
VAST 4.2 allow multiple UniversalAdID elements to be passed in a VAST response

### ISSUE THREAD

**Issue by radiantmediaplayer** [dailymotion/vast-client-js#376]
Hi,

Great work on this plugin. VAST 4.2 specs states: 

> With VAST 4.2 we now allow multiple UniversalAdID elements to be passed in a VAST response

Right now creative.universalAdId returns an Object `{idRegistry: String, value: String}` in vast-client-js 3.0 and not an Array of Object. If you could add this feature to support multiple UniversalAdID that would be great. You can find a test VAST tag for this at https://github.com/InteractiveAdvertisingBureau/VAST_Samples/blob/master/VAST%204.2%20Samples/Category-test.xml.

Thanks
Arnaud

**Comment by ZacharieTFR** [comment]
Hi Arnaud, 
Thank you for reporting this issue, we will look at it asap ! But if you wish to speed up the process, you can contribute to the repo following our [guidelines](https://github.com/dailymotion/vast-client-js/blob/master/docs/CONTRIBUTING.md#pull-requests).

**Comment by ZacharieTFR** [comment]
Hello, as it's a breaking change the fix has been merged in the [4.X branch](https://github.com/dailymotion/vast-client-js/tree/4.X). We will wait a bit before doing the next major release, in the meantime you can already build and use the [4.X branch](https://github.com/dailymotion/vast-client-js/tree/4.X).
Don't hesitate to contact us if you encounter any difficulties.
