### ISSUE TITLE
ViewableImpression tags in Wrapper are not collected

### ISSUE THREAD

**Issue by radiantmediaplayer** [dailymotion/vast-client-js#378]
Hi,

Right now the lib properly handles ViewableImpression tag when in an InLine tag like at: https://www.radiantmediaplayer.com/vast/tags/inline-linear-viewable.xml, but when the ViewableImpression data is in a Wrapper tag it seems the lib is just discarding those information. VAST 4.2 spec indicates that this should be possible to have ViewableImpression in Wrapper and the IAB provides a sample at https://github.com/InteractiveAdvertisingBureau/VAST_Samples/blob/master/VAST%204.0%20Samples/Viewable_Impression-test.xml. 
That would be great if you could take a look into it. 

Arnaud

**Comment by ZacharieTFR** [comment]
Hi Arnaud,
Thank you for reporting this issue, we will look at it asap !

**Comment by XavM** [comment]
Hello @ZacharieTFR,

It seams the Viewable impression tracker is still not firing when in a Wrapper tag.

Any news or eta for a fix ?

Regards,

**Comment by mouchii** [comment]
Hello,

Any update on this ?

**Comment by ZacharieTFR** [comment]
Hello, sorry for the late answer but it has been fixed in the [4.X branch](https://github.com/dailymotion/vast-client-js/tree/4.X). You can use or do a build based on this branch. We will release soon the 4.X branch though

**Comment by radiantmediaplayer** [comment]
Thanks I will look into v4 when it is released.
