### ISSUE TITLE
Unable to parse VAST Xml from IAB

### ISSUE THREAD

**Issue by olgunkaya** [dailymotion/vast-client-js#393]
I am trying to use the VASTClient as below but gettin "Invalid VAST XMLDocument" error. As you can see the file is from Bureau github repo. Which should be a valid one. 

  ```
import {VASTClient, VASTParser} from 'vast-client';
....

const vastClient = new VASTClient();

vastClient
    .get(
      'https://raw.githubusercontent.com/InteractiveAdvertisingBureau/VAST_Samples/master/VAST%204.0%20Samples/Inline_Simple.xml',
    )
    .then((res) => {
      // Do something with the parsed VAST response
      console.log('RESTEST', res);
    })
    .catch((err) => {
      // Deal with the error
      console.log('ERROR', err);
    });
```

Can someone help me to understand, why I am getting this ? I tried to parse the xml manually using some xml parsers like the one from npm package "react-xml-parser" and it did not throw error.

**Comment by ZacharieTFR** [comment]
Hello, which version of vast-client are you using ?

**Comment by olgunkaya** [comment]
I tried the latest version as well. Even forked your master branch and pushed as an npm package :)

**Comment by edrpls** [comment]
@olgunkaya have you tried in incognito, or disabling ad blockers? The request may be getting blocked by an ad blocker extension.

**Comment by olgunkaya** [comment]
@edrpls I am trying with react-native in a real device. Is that possible ?

**Comment by edrpls** [comment]
In that case, I don't think that's the issue unless there is an ad blocker or filter on your network, but I suppose you would know that.

Could it be the device itself blocking it? I tried the provided VAST with [my player](https://gumgum.github.io/gg-ez-vp/demo), which uses VAST-Client, and it loaded without problems.

**Comment by olgunkaya** [comment]
well I am **remote** debugging the app on my pc browser while it is actually running on my phone. I will (still don't think but) disable the ad blockers on my browser too and give it a try.

**Comment by PaulineMDaily** [comment]
Hi @olgunkaya ! Sorry for the delayed answer, we never tried to run the project in react-native, the last issue reported for react-native was: https://github.com/dailymotion/vast-client-js/issues/305#issuecomment-529506623. The error is not the same, but if you still face the issue you might want to take a look. We tried to reproduce on master and with the latest version released but did not manage. Could you tell us if you still get the error?

**Comment by ZacharieTFR** [comment]
Hello @olgunkaya, any new on this or should I close this thread ? 
Thanks

**Comment by olgunkaya** [comment]
Hi, thx for checking in. I think we can cloae this. Sorry for the delay. 

Teşekkürler
Olgun Kaya
