### ISSUE TITLE
VAST 4.1 Macros and Ad Request

### ISSUE THREAD

**Issue by cizmo** [dailymotion/vast-client-js#397]
Hello,

due to VAST 4.1 specification macros have been completly revamped. 
According to #336 you have added another VAST 4.1 macros, which is fine, but as i check source code you only applying them to the tracking URL, not request URL. Does it means that in order to use macros in VAST request URL, I should add those same macros as my custom addURLTemplateFilter? 

Thanks in advance!

**Comment by ZacharieTFR** [comment]
Hello, 
Yes you are absolutly right, you can find the documentation [here](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-parser.md#addurltemplatefilterfilter).
