### ISSUE TITLE
setProgress causes a memory leak under certain condition

### ISSUE THREAD

**Issue by fingerartur** [dailymotion/vast-client-js#413]
`setProgress()` method of VAST Tracker causes a memory leak under specific condition.

Sadly I do not know exactly how to recreate this issued at this moment, I will get back with more info later.

I have a feeling that the issue may be related on `skipDelay === 0`, but I will have to investigate more to reproduce it.

**Comment by ZacharieTFR** [comment]
Hello @fingerartur, were you able to reproduce/investigate ? 
Thanks

**Comment by fingerartur** [comment]
Hi, sorry guys, I have not been able to dig deeper. What we did in our project was we upgraded to `"@dailymotion/vast-client": "^3.3.0",` and it seems that the issue has been fixed by the upgrade.
So I think we can close this one, if I run into it again I will let you know. :)
