### ISSUE TITLE
[QUESTION] How to write automated tests for vast tracking

### ISSUE THREAD

**Issue by chamino** [dailymotion/vast-client-js#427]
Hi, I'm trying to write integration tests to test that events are sent properly. However, intercept/spy doesn't work in cypress, probably because it's not XHR . Do you have a recommended way to write integration tests?

**Comment by yukikofirework** [comment]
Hi, thank you for the tip it works! I was trying to get the callCount which didn't work, but at the end we created an object on window and pushed events there during integration tests so we can verify (Like how GTM works).

**Comment by ZacharieTFR** [comment]
You're welcome ! 👍 I will close this issue then, please feel free to open another one if needed.
