### ISSUE TITLE
SSAI implementation

### ISSUE THREAD

**Issue by savke24** [dailymotion/vast-client-js#430]
Hi i have idea of trying to implement something like or exactly like Server side adding Ads.

Basically  i would like to use this library on client side to fetch VAST tag (which i was able to do) and get ad content url (mp4 file)it self which i than forward to API which is doing slicing in .ts chunks and updating m3u8 manifest.(some basic version of that logic i already have).

What i don't know and can't figure it out is does Vast Tracker require some player object and player events so impression can be successfully executed or it can work with out it and how?

Thank You. 

0

**Comment by ZacharieTFR** [comment]
Hello, it seems you're describing the same issue than #429. 

No it doesn't need a player object to work but it will need to be initialized with your instance of vast client (optional), the ad object and the creative that you will play. See https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md for more examples

```js
// with a vastClient instance
const vastTracker = new VASTTracker(vastClient, ad, creative);
// without a vastClient instance
const vastTracker = new VASTTracker(null, ad, creative);
``` 
Then you will be responsible to call the VASTTracker [trackImpression](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md#trackimpressionmacros) method at the right time to fire the corresponding [VAST trackers](https://iabtechlab.com/wp-content/uploads/2019/06/VAST_4.2_final_june26.pdf#page=42). You can check the video tag events on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#events) to find the one that correspond the most to your need. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#events

```js
player.addEventListener('loadeddata', () => {
  vastTracker.trackImpression()
});
```

For other trackers feel free to check all VASTTracker [public methods](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md#public-methods--) available

Let me know, if it helps 😉

**Comment by savke24** [comment]
Hi @ZacharieTFR  thank You for Your respond.

When you say : " 

Then you will be responsible to call the VASTTracker [trackImpression](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md#trackimpressionmacros) method at the right time to fire the corresponding trackers.
"

What do you mean by that ?
If call trackImpression method outside of player event, will be fired correctly and before calling that method does video needs to be played ?

**Comment by ZacharieTFR** [comment]
Yes, it will be fired correctly if the VAST contains an `<Impression>` element. But the [IAB VAST specification](https://iabtechlab.com/wp-content/uploads/2019/06/VAST_4.2_final_june26.pdf#page=42) says:

> All \<Impression\> URIs in the InLine response and any Wrapper responses preceding it should be triggered at the same time when the impression for the ad occurs, or as close in time as possible to when the impression occurs, to prevent impression-counting discrepancies.

so you must call [trackImpression](https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-tracker.md#trackimpressionmacros) as soon as the ad is displayed.
