### ISSUE TITLE
using pre bundled version of Node

### ISSUE THREAD

**Issue by staminna** [dailymotion/vast-client-js#439]
Hi.

I found the old links broken for https://github.com/dailymotion/vast-client-js/blob/master/webpack.config.js#L6-L13

and

https://github.com/dailymotion/vast-client-js/pull/239 has no example code.

How can I use using pre bundled version of Node? Perhaps a package.json file and webpack config file could help

**Comment by ZacharieTFR** [comment]
Hello I added an example on how to use the pre-bundled version, let me know if it help https://github.com/dailymotion/vast-client-js#node
If you still have an issue please feel free to reopen 😉
