### ISSUE TITLE
adSlotID should be adSlotId

### ISSUE THREAD

**Issue by privaloops** [dailymotion/vast-client-js#445]
Following the IAB specs, "adSlotID" should be "adSlotId"
[there](https://github.com/dailymotion/vast-client-js/blob/1c8ee18cbb89467c82f1bf61f6bed7431852842b/src/companion_ad.js#L12)

Thank you !

**Comment by ZacharieTFR** [comment]
Hello, closing this issue as it has been fixed in the 5.0 version. See https://github.com/dailymotion/vast-client-js/releases/tag/5.0.0 for full changelog
