### ISSUE TITLE
Bug: Fallback not working if top Ad Elements returns empty Vast or fails in case of multiple Ad Elements

### ISSUE THREAD

**Issue by shubham-si** [dailymotion/vast-client-js#465]
https://github.com/dailymotion/vast-client-js/blob/master/src/parser/vast_parser.js#L461C25-L461C25

`const resolvedAds = util.flatten(unwrappedAds);` default to `[]`  [Link](https://github.com/dailymotion/vast-client-js/blob/master/src/util/util.js#L216)

`if (!resolvedAds && this.remainingAds.length > 0) {`

There seems to be a issue here `!resolvedAds`. Since `!Array<T>` gives `false` always, thus the code within if will not be executed at all.

So If any Ad element (going from top to bottom) fails to fetch xml or return empty vast, it will not fallback to next Ad Element.

```xml
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
<Ad>
<Wrapper fallbackOnNoAd="true">
<AdSystem/>
<Error>
<![CDATA[ https://error-pixel?[ERRORCODE] ]]>
</Error>
<VASTAdTagURI>
<![CDATA[ ]]>
</VASTAdTagURI>
<Extensions>
<Extension type="waterfall" fallback_index="0"/>
</Extensions>
</Wrapper>
</Ad>
<Ad>
<Wrapper fallbackOnNoAd="true">
<AdSystem/>
<Error>
<![CDATA[ https://error-pixel?[ERRORCODE] ]]>
</Error>
<VASTAdTagURI>
<![CDATA[ does-not-exist ]]>
</VASTAdTagURI>
<Extensions>
<Extension type="waterfall" fallback_index="1"/>
</Extensions>
</Wrapper>
</Ad>
<Ad>
<Wrapper>
<AdSystem/>
<Error>
<![CDATA[ https://error-pixel?[ERRORCODE] ]]>
</Error>
<VASTAdTagURI>
<![CDATA[ https://glomex.github.io/vast-ima-player/linear-ad.xml ]]>
</VASTAdTagURI>
<Extensions>
<Extension type="waterfall" fallback_index="2"/>
</Extensions>
</Wrapper>
</Ad>
</VAST>
```

**Fix:**  `if (resolvedAds.length === 0 && this.remainingAds.length > 0) {`

so that if resolvedAds fails and we have remainingAds, can be proceeded with them.

**Comment by Rapha0511** [comment]
Hello ! 
thank you for reporting this issue, we will take a look at it asap !

**Comment by shubham-si** [comment]
hello @Rapha0511 any update on this?

**Comment by shubham-si** [comment]
@Rapha0511 is the bug fixed ?
