### ISSUE TITLE
webpack module not found

### ISSUE THREAD

**Issue by mdellanave** [dailymotion/vast-client-js#480]
Hi, 
since I updated to version 6.0.1, webpack is no longer able to build the bundle because of this errors

![image](https://github.com/user-attachments/assets/591d9038-5ac8-4276-95f8-e5a978d06276)

I'm importing VASTClient and VASTracker in this way
![image](https://github.com/user-attachments/assets/4ed34288-c1c3-4327-837d-c744faec5e7b)

using this settings for webpack with babel

![image](https://github.com/user-attachments/assets/c2afc819-aeea-4e43-b7a4-211b539b0a8c)
![image](https://github.com/user-attachments/assets/3bb525d5-eca9-4b50-bfdf-271bfb2a0889)

any idea?

**Comment by ZacharieTFR** [comment]
Hello what version of webpack are you using ?

**Comment by mdellanave** [comment]
![image](https://github.com/user-attachments/assets/f28d0d2e-7ad1-4fc4-9a8f-6b92592bb26d)

**Comment by privaloops** [comment]
same here

**Comment by privaloops** [comment]
I've got the same problem with a player trying to load the lib with dynamic import in a nextjs project. Need to bundle the lib :(

**Comment by mdellanave** [comment]
> I've got the same problem with a player trying to load the lib with dynamic import in a nextjs project. Need to bundle the lib :(

I had to do the same in another project for another library and I used rollup, should I use the same approach or do you know if there's a way to do it directly with webpack?

**Comment by mdellanave** [comment]
I think I found a way, simply changing the path of the import to this
![image](https://github.com/user-attachments/assets/991150d7-ba7e-4ff7-a68a-24d811aa3c25)
Now webpack build my project without errors, but I got an error using the function vastClientInstance.getParser().addURLTemplateFilter, I don't know if it's because the breaking changes between 5 and 6 version or it's due to the way I'm importing the VASTClient object, any idea?

**Comment by ZacharieTFR** [comment]
Hello do you still have the issue ? If that's not the case I will close this issue.

**Comment by mdellanave** [comment]
@ZacharieTFR I found a solution so for me you can close the issue.
Thank you
