### ISSUE TITLE
Problem when parsing empty creative

### ISSUE THREAD

**Issue by carpasse** [dailymotion/vast-client-js#61]
I have only experimented this error from time to time whenever I got an empty creative

```
   <Creative><![CDATA[]]></Creative>
```

I imagine that is not very common but still it throws an error from time to time that prevents the ads from loading.

I have tracked down the error to the '_parse' function in https://github.com/dailymotion/vast-client-js/blob/master/src/parser.coffee

on line 122 you have

```
creative.trackingEvents[eventName] or= []
```

This line compiles to 

```
(_base = creative.trackingEvents)[eventName] || (_base[eventName] = []);
```

having _base variable declared at the beginning of the function with undefined value
So if 
```
creative.trackingEvents)[eventName]
```
is undefined, it tries to define
```
_base[eventName] = [])
```

and since _base is undefine, the virtual machine throws an error.

Can you please take a look at it??

**Comment by rs** [comment]
Dup of #59 (please reopen if not)
