### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by StevenLangbroek** [dailymotion/vast-client-js#76]
Hey guys,

Mind publishing this on NPM? If you need PR or help let me know ok?

Thnx,

- Steven

**Comment by StevenLangbroek** [comment]
Some issues to fix:

- [ ] Include entry point in package.json
- [ ] Build to CommonJS

**Comment by nathschmidt** [comment]
+1 

PR #83  actually adds support for publishing this module. All that is needed now is a dailymotion NPM account and `npm publish`.

**Comment by rs** [comment]
Done, thx for your help
