### ISSUE TITLE
Architecture issue

### ISSUE THREAD

**Issue by StevenLangbroek** [dailymotion/vast-client-js#79]
Hey guys,

I'm trying to use this in a componentised way (we implement this in our platform, but I'm building a standalone debugger). What I want to do should be relatively straight forward if it wasn't so tightly coupled:
- Show choice: `By URL` or `By XML`
- If `By XML`, show CodeMirror editor and have our employees input XML
- If `By URL`, run through `VASTClient.client`.

The problem here is when users choose `By XML`. Because of the way the client is structured, there's no way to just parse XML to the Object literal format you use, without invoking `URLHandler.get`. This seems like "bad architecture". The XML parser should be a static method on `Parser`, and be invokable without needing to call `URLHandler.get`. Would you be interested in a PR for this?

Thanks!

**Comment by rs** [comment]
Yes it would be interested to decouple the URL handler. Feel free to PR.
