### ISSUE TITLE
Single Wrapper XML File does not load (GIST)

### ISSUE THREAD

**Issue by spodlecki** [dailymotion/vast-client-js#86]
VAST XML Samples: https://gist.github.com/spodlecki/6808e73003c1bcbcf9a4 

_Loads properly:_ Given a single wrapper **and** a single inline ad, the second XML file loads fine and plays both ads (see file document_with_one_inline_and_one_wrapper_ad.xml)

_Fails to load ad:_ Given a VAST 2.0 with a single wrapper ad, the Wrapper XML file does not load (see file document_with_one_wrapper_ad.xml)

**Comment by rs** [comment]
I'm not sure to follow. Did you spot where the issue is?

**Comment by spodlecki** [comment]
I unfortunately don't know where the problem is with the wrapper not loading. I can only tell you where it failed from looking at what the browser is doing.

When it runs the inline + wrapper, it loads the the XML file -- but when its just the wrapper, its not loading via http
