### ISSUE TITLE
progress event doesnt supported

### ISSUE THREAD

**Issue by selam** [dailymotion/vast-client-js#87]
VAST 3.0 spec says we can track ads progress with quartiles and progress event in same time but vast client doesn't support progress event

**Comment by rs** [comment]
Both kinds of trackers should be supported. See https://github.com/dailymotion/vast-client-js/blob/master/src/tracker.coffee#L58-L70

**Comment by selam** [comment]
ohh yes my mistake i was using 1.3.3 release instead of master.  I close this becouse it's invalid.
