### ISSUE TITLE
pause, complete, resume events fired when ads finished playing

### ISSUE THREAD

**Issue by selam** [dailymotion/vast-client-js#88]
When ads finish to play vast-client.js fires pause, complete and resume events (in that order) except complete none of them related with ad file. 

I am not sure this bug related with vast-client it self or other plugin called videojs.vast.js.

**Comment by rs** [comment]
The pause and resume events are not triggered if the related methods are not called on the VAST client tracker.

**Comment by selam** [comment]
I can't figure out  why and how pause event triggered but here is what i found.

videojs.vast.js attach a callback to pause event, when it fires, execute events from vast-client.js,

this event never fired by user during the tests (that means we dont click to pause button) however after ads finish pause event triggered. i cannot find source this event (i comment out all pause() related methods in video.js, videojs.ads.js vast-client.js and videojs.vast.js) 

pause event fired when currentTime() and duration is equal.

doesnt matter video is autoplay but it never fires when video tag has  loop attribute. 

(there is a another bug here, if video is in loop so ad video in loop too, but i am not sure this is the right plase or videojs.ads.js) 

i tested with firefox and chrome they give the same results. maybe chrome and firefox pause videos before the stoped? i solve this problem with basicly check duration and currentTime if they equal so pause event not related with user.

**Comment by rs** [comment]
VAST client does't manage the video tag. What you describe is handled the videojs plugin you are using.

**Comment by michaelvial** [comment]
not a `vast-client` bug, closing
