### ISSUE TITLE
Support for parsing <Extensions> in <InLine>

### ISSUE THREAD

**Issue by nerdynick** [dailymotion/vast-client-js#90]
We have a use case where we need to get at the <Extensions> values within <InLine>.  Seeing as by spec <Extensions> value can be any valid XML. I'm proposing a very generic parsed response. It'd be an array of extension elements each with name, value, attributes where they are string, string, object respectively. It'll be up to the end user to parse the value of each extension any farther as that would be custom code for the situation.

**Comment by nerdynick** [comment]
I have a functioning change set for this. Just working on testing and validation before submitting pull request.

**Comment by nerdynick** [comment]
PR submitted

**Comment by rs** [comment]
You may want to have the unparsed arbitrary xml in the value.

**Comment by nerdynick** [comment]
Which value? VastAd.extensions or VASTAdExtension.value? VASTAdExtension.value should be the raw text value of anything below it including XML.

Was just thinking about adding extensionsRaw to the VastAd as a just incase.
