### ISSUE TITLE
Ad Pod vs Standalone Ad

### ISSUE THREAD

**Issue by zrehmani** [dailymotion/vast-client-js#94]
As far as I understand VAST 3.0 spec - I thought that ads with sequence attribute are to be in group (pod) to be played as a group while stand alone ads - those without sequence should be separate.  For example if any of the ad inside pod fail to load - player can chose one from the stand alone ad what spec calls ad buffet.  From my initial test - it seems like there is no distinction made by the DMVAST client between ads that belong to a pod and those that are stand alone ads.  Am I mistaken in thinking they should be separated?  I'd appreciate your thoughts on this.

**Comment by rs** [comment]
You're right, ad pods aren't implemented yet. If you want to propose a PR, welcome.

**Comment by zrehmani** [comment]
Thanks for getting back.  Hope to see this implemented in near future.  I was test driving it and will check in future again.

**Comment by eliamaino-fp** [comment]
AdPods support is now available in the `2.0` version of the library: https://github.com/dailymotion/vast-client-js/releases/tag/2.0.0
