### ISSUE TITLE
VAST 4.0

### ISSUE THREAD

**Issue by duilio** [dailymotion/vast-client-js#98]
Is there any plan for supporting VAST 4.0?

http://www.iab.com/guidelines/digital-video-ad-serving-template-vast-4-0/

**Comment by Mulder90** [comment]
+1 for this

**Comment by ufucuk** [comment]
When they release xsd for VAST 4 I'll implement it!

**Comment by duilio** [comment]
Seems like a draft was released:

https://github.com/InteractiveAdvertisingBureau/VAST_UseCases/blob/master/vast4_draft.xsd

I don't see the official release for vast3 xsd so I don't know if it will be released anything better than this. :-/

**Comment by MikeSperone** [comment]
Any updates on plans to add VAST 4.0 support?  The documentation still only says it's compatible up to 3.0

**Comment by eliamaino-fp** [comment]
Hi @MikeSperone it's still in our to-do list but unfortunately not in the roadmap yet. We'd like to start the development as soon as possible (plus 4.1 spec went out in the meantime).

I'll keep you all posted in this thread :)

**Comment by sndpl** [comment]
@eliamaino-fp do you accept partial VAST 4 support? for a project we currently only use the parser/tracker and have implemented universalId, conditionalAd, ViewableImpression, category elements. So no client fixes for VAST 4.

**Comment by unglud** [comment]
@sndpl hey, could you please share your code with us with universalId, conditionalAd, ViewableImpression, category elements? Would be very appreciated!

**Comment by ZacharieTFR** [comment]
Hello, 
Version 3.0 is officially released and we now support VAST 4 ! 🎉
